// Code generated by "stringer -type DSLNestAction"; DO NOT EDIT.

package dsl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DSLNestActionMatch-0]
	_ = x[DSLNestActionPushNext-1]
	_ = x[DSLNestActionPop-2]
}

const _DSLNestAction_name = "DSLNestActionMatchDSLNestActionPushNextDSLNestActionPop"

var _DSLNestAction_index = [...]uint8{0, 18, 39, 55}

func (i DSLNestAction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DSLNestAction_index)-1 {
		return "DSLNestAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DSLNestAction_name[_DSLNestAction_index[idx]:_DSLNestAction_index[idx+1]]
}
