// Code generated by "stringer -type LangSpecLexerTokenType"; DO NOT EDIT.

package dsl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokEOF-1]
	_ = x[TokWhitespace-2]
	_ = x[TokLineComment-3]
	_ = x[TokBlockComment-4]
	_ = x[TokVarRef-5]
	_ = x[TokDashes-6]
	_ = x[TokBraceOpen-7]
	_ = x[TokBraceClose-8]
	_ = x[TokSemicolon-9]
	_ = x[TokDot-10]
	_ = x[TokChainSeparator-11]
	_ = x[TokAssignment-12]
	_ = x[TokEqualsOperator-13]
	_ = x[TokMetaSection-14]
	_ = x[TokPipe-15]
	_ = x[TokConcat-16]
	_ = x[TokRange-17]
	_ = x[TokStar-18]
	_ = x[TokSeparator-19]
	_ = x[TokStringLiteral-20]
	_ = x[TokRegexLiteral-21]
	_ = x[TokCharLiteral-22]
	_ = x[TokVersion-23]
	_ = x[TokInteger-24]
	_ = x[TokIdentifier-25]
	_ = x[TokKWLSpec-26]
	_ = x[TokKWLex-27]
	_ = x[TokKWPattern-28]
	_ = x[TokKWPragma-29]
	_ = x[TokKWTool-30]
	_ = x[TokKWTrue-31]
	_ = x[TokKWFalse-32]
}

const _LangSpecLexerTokenType_name = "TokEOFTokWhitespaceTokLineCommentTokBlockCommentTokVarRefTokDashesTokBraceOpenTokBraceCloseTokSemicolonTokDotTokChainSeparatorTokAssignmentTokEqualsOperatorTokMetaSectionTokPipeTokConcatTokRangeTokStarTokSeparatorTokStringLiteralTokRegexLiteralTokCharLiteralTokVersionTokIntegerTokIdentifierTokKWLSpecTokKWLexTokKWPatternTokKWPragmaTokKWToolTokKWTrueTokKWFalse"

var _LangSpecLexerTokenType_index = [...]uint16{0, 6, 19, 33, 48, 57, 66, 78, 91, 103, 109, 126, 139, 156, 170, 177, 186, 194, 201, 213, 229, 244, 258, 268, 278, 291, 301, 309, 321, 332, 341, 350, 360}

func (i LangSpecLexerTokenType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_LangSpecLexerTokenType_index)-1 {
		return "LangSpecLexerTokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LangSpecLexerTokenType_name[_LangSpecLexerTokenType_index[idx]:_LangSpecLexerTokenType_index[idx+1]]
}
