// Code generated by "stringer -type LangSpecParserNodeKind"; DO NOT EDIT.

package dsl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeError-1]
	_ = x[NodeProgram-2]
	_ = x[NodeHeader-3]
	_ = x[NodeLexSection-4]
	_ = x[NodeDSLName-5]
	_ = x[NodeVersion-6]
	_ = x[NodeLSPECName-7]
	_ = x[NodeIdentifier-8]
	_ = x[NodeLexKeyword-9]
	_ = x[NodeLexRule-10]
	_ = x[NodeLexRuleTokenName-11]
	_ = x[NodeLexRuleScope-12]
	_ = x[NodeLexRulePattern-13]
}

const _LangSpecParserNodeKind_name = "NodeErrorNodeProgramNodeHeaderNodeLexSectionNodeDSLNameNodeVersionNodeLSPECNameNodeIdentifierNodeLexKeywordNodeLexRuleNodeLexRuleTokenNameNodeLexRuleScopeNodeLexRulePattern"

var _LangSpecParserNodeKind_index = [...]uint8{0, 9, 20, 30, 44, 55, 66, 79, 93, 107, 118, 138, 154, 172}

func (i LangSpecParserNodeKind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_LangSpecParserNodeKind_index)-1 {
		return "LangSpecParserNodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LangSpecParserNodeKind_name[_LangSpecParserNodeKind_index[idx]:_LangSpecParserNodeKind_index[idx+1]]
}
