// Code generated by "stringer -type LangSpecParserNodeKind"; DO NOT EDIT.

package dsl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeError-1]
	_ = x[NodeProgram-2]
	_ = x[NodeHeader-3]
	_ = x[NodeHeaderContent-4]
	_ = x[NodeBody-5]
	_ = x[NodeDSLName-6]
	_ = x[NodeVersion-7]
	_ = x[NodeLSPECName-8]
	_ = x[NodeIdentifier-9]
}

const _LangSpecParserNodeKind_name = "NodeErrorNodeProgramNodeHeaderNodeHeaderContentNodeBodyNodeDSLNameNodeVersionNodeLSPECNameNodeIdentifier"

var _LangSpecParserNodeKind_index = [...]uint8{0, 9, 20, 30, 47, 55, 66, 77, 90, 104}

func (i LangSpecParserNodeKind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_LangSpecParserNodeKind_index)-1 {
		return "LangSpecParserNodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LangSpecParserNodeKind_name[_LangSpecParserNodeKind_index[idx]:_LangSpecParserNodeKind_index[idx+1]]
}
