// Code generated by "stringer -type LangSpecLexerTokenType"; DO NOT EDIT.

package dsl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokEOF-1]
	_ = x[TokWhitespace-2]
	_ = x[TokDashes-3]
	_ = x[TokHeaderSeparator-4]
	_ = x[TokStringLiteral-5]
	_ = x[TokVersion-6]
	_ = x[TokKWLSpec-7]
	_ = x[TokKWDeclare-8]
	_ = x[TokKWLexerTokenTypes-9]
	_ = x[TokBraceOpen-10]
	_ = x[TokBraceClose-11]
	_ = x[TokSemicolon-12]
	_ = x[TokComma-13]
	_ = x[TokComment-14]
}

const _LangSpecLexerTokenType_name = "TokEOFTokWhitespaceTokDashesTokHeaderSeparatorTokStringLiteralTokVersionTokKWLSpecTokKWDeclareTokKWLexerTokenTypesTokBraceOpenTokBraceCloseTokSemicolonTokCommaTokComment"

var _LangSpecLexerTokenType_index = [...]uint8{0, 6, 19, 28, 46, 62, 72, 82, 94, 114, 126, 139, 151, 159, 169}

func (i LangSpecLexerTokenType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_LangSpecLexerTokenType_index)-1 {
		return "LangSpecLexerTokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LangSpecLexerTokenType_name[_LangSpecLexerTokenType_index[idx]:_LangSpecLexerTokenType_index[idx+1]]
}
