// Code generated by "stringer -type LangSpecParserNodeKind"; DO NOT EDIT.

package dsl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeError-1]
	_ = x[NodeProgram-2]
	_ = x[NodeHeader-3]
	_ = x[NodeBody-4]
	_ = x[NodeDeclarationBlocks-5]
	_ = x[NodeDeclarationBlock-6]
	_ = x[NodeList-7]
	_ = x[NodeDSLName-8]
	_ = x[NodeVersion-9]
	_ = x[NodeLSPECName-10]
	_ = x[NodeDeclareIdentifier-11]
	_ = x[NodeIdentifier-12]
}

const _LangSpecParserNodeKind_name = "NodeErrorNodeProgramNodeHeaderNodeBodyNodeDeclarationBlocksNodeDeclarationBlockNodeListNodeDSLNameNodeVersionNodeLSPECNameNodeDeclareIdentifierNodeIdentifier"

var _LangSpecParserNodeKind_index = [...]uint8{0, 9, 20, 30, 38, 59, 79, 87, 98, 109, 122, 143, 157}

func (i LangSpecParserNodeKind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_LangSpecParserNodeKind_index)-1 {
		return "LangSpecParserNodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LangSpecParserNodeKind_name[_LangSpecParserNodeKind_index[idx]:_LangSpecParserNodeKind_index[idx+1]]
}
