// Code generated by "stringer -type RuleAction"; DO NOT EDIT.

package editor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACTION_PUSH-0]
	_ = x[ACTION_POP-1]
	_ = x[ACTION_SET-2]
	_ = x[ACTION_MATCH-3]
	_ = x[ACTION_NONE-4]
	_ = x[ACTION_EMBED-5]
}

const _RuleAction_name = "ACTION_PUSHACTION_POPACTION_SETACTION_MATCHACTION_NONEACTION_EMBED"

var _RuleAction_index = [...]uint8{0, 11, 21, 31, 43, 54, 66}

func (i RuleAction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RuleAction_index)-1 {
		return "RuleAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RuleAction_name[_RuleAction_index[idx]:_RuleAction_index[idx+1]]
}
