// Code generated by LangSpec. DO NOT EDIT.

package compiler

import (
	"lexarch"
	"strconv"
)

// Token represents a Token generated by LangSpec (IDs match compiler symbol table).
type Token = lexarch.TokenKind

const (
	TokBlockComment Token = 2
	TokBraceClose Token = 3
	TokBraceOpen Token = 4
	TokBracketClose Token = 5
	TokBracketOpen Token = 6
	TokChainSeparator Token = 7
	TokCharLiteral Token = 8
	TokColon Token = 9
	TokComma Token = 10
	TokDashes Token = 11
	TokDot Token = 12
	TokEOF Token = 13
	TokEqualsOperator Token = 14
	TokIdentifier Token = 15
	TokInteger Token = 16
	TokKWAs Token = 17
	TokKWCall Token = 18
	TokKWEmbed Token = 19
	TokKWExport Token = 20
	TokKWFalse Token = 21
	TokKWIgnore Token = 22
	TokKWImplicit Token = 23
	TokKWImport Token = 24
	TokKWInfix Token = 25
	TokKWLSpec Token = 26
	TokKWLex Token = 27
	TokKWLocal Token = 28
	TokKWNest Token = 29
	TokKWPair Token = 30
	TokKWParse Token = 31
	TokKWPattern Token = 32
	TokKWPop Token = 33
	TokKWPostfix Token = 34
	TokKWPragma Token = 35
	TokKWPratt Token = 36
	TokKWPrecedence Token = 37
	TokKWPredict Token = 38
	TokKWPrefix Token = 39
	TokKWPrimary Token = 40
	TokKWPush Token = 41
	TokKWRule Token = 42
	TokKWSet Token = 43
	TokKWState Token = 44
	TokKWSync Token = 45
	TokKWTemplate Token = 46
	TokKWTool Token = 47
	TokKWTransparent Token = 48
	TokKWTrue Token = 49
	TokKWUsing Token = 50
	TokKWVirtual Token = 51
	TokLineComment Token = 52
	TokMetaSection Token = 53
	TokNegation Token = 54
	TokOptional Token = 55
	TokPairReference Token = 56
	TokParameter Token = 57
	TokParenClose Token = 58
	TokParenOpen Token = 59
	TokPipe Token = 60
	TokPlus Token = 61
	TokRange Token = 62
	TokRegexLiteral Token = 63
	TokSemicolon Token = 64
	TokStar Token = 65
	TokStringLiteral Token = 66
	TokTypeNode Token = 67
	TokTypePair Token = 68
	TokTypePrattExpr Token = 69
	TokTypeRule Token = 70
	TokTypeToken Token = 71
	TokVersion Token = 72
	TokWhitespace Token = 73
)

var TokenNames = [...]string{
	"TokBlockComment",
	"TokBraceClose",
	"TokBraceOpen",
	"TokBracketClose",
	"TokBracketOpen",
	"TokChainSeparator",
	"TokCharLiteral",
	"TokColon",
	"TokComma",
	"TokDashes",
	"TokDot",
	"TokEOF",
	"TokEqualsOperator",
	"TokIdentifier",
	"TokInteger",
	"TokKWAs",
	"TokKWCall",
	"TokKWEmbed",
	"TokKWExport",
	"TokKWFalse",
	"TokKWIgnore",
	"TokKWImplicit",
	"TokKWImport",
	"TokKWInfix",
	"TokKWLSpec",
	"TokKWLex",
	"TokKWLocal",
	"TokKWNest",
	"TokKWPair",
	"TokKWParse",
	"TokKWPattern",
	"TokKWPop",
	"TokKWPostfix",
	"TokKWPragma",
	"TokKWPratt",
	"TokKWPrecedence",
	"TokKWPredict",
	"TokKWPrefix",
	"TokKWPrimary",
	"TokKWPush",
	"TokKWRule",
	"TokKWSet",
	"TokKWState",
	"TokKWSync",
	"TokKWTemplate",
	"TokKWTool",
	"TokKWTransparent",
	"TokKWTrue",
	"TokKWUsing",
	"TokKWVirtual",
	"TokLineComment",
	"TokMetaSection",
	"TokNegation",
	"TokOptional",
	"TokPairReference",
	"TokParameter",
	"TokParenClose",
	"TokParenOpen",
	"TokPipe",
	"TokPlus",
	"TokRange",
	"TokRegexLiteral",
	"TokSemicolon",
	"TokStar",
	"TokStringLiteral",
	"TokTypeNode",
	"TokTypePair",
	"TokTypePrattExpr",
	"TokTypeRule",
	"TokTypeToken",
	"TokVersion",
	"TokWhitespace",
}

func TokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "Token(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return TokenNames[t-2]
}

func TokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "", false
	}
	return TokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(TokenTokenKindStringResolver)
}

// Node represents a Node generated by LangSpec (IDs match compiler symbol table).
type Node uint32

const (
	DUMMY_CHOICE_FOR_PRAGMA_VALUES Node = 1
	DUMMY_CHOICE_IDENT_MAP_BASE Node = 2
	DUMMY_CHOICE_NEST Node = 3
	DUMMY_CHOICE_PARSE_BLOCK_CHOICE Node = 4
	DUMMY_CHOICE_PARSE_BLOCK_LIST Node = 5
	DUMMY_CHOICE_VIRTUAL_MAPPING Node = 6
	ERROR_NODE Node = 7
	HEADER Node = 8
	HEADER_CONTENT Node = 9
	IMPORT_DEFINITION Node = 10
	IMPORT_DEFINITION_LIST Node = 11
	IMPORT_SECTION Node = 12
	IMPORT_SECTION_BLOCK_NEST Node = 13
	LEX_RULE Node = 14
	LEX_RULE_LIST Node = 15
	LEX_RULE_PATTERN Node = 16
	LEX_RULE_PATTERN_USING_LEX Node = 17
	LEX_RULE_PATTERN_USING_NEST Node = 18
	LEX_RULE_PATTERN_USING_PARSE_SEGMENT Node = 19
	LEX_RULE_STATE_MUTATION Node = 20
	LEX_RULE_STATE_MUTATION_KIND Node = 21
	LEX_SECTION Node = 22
	LEX_SECTION_BLOCK_NEST Node = 23
	META_KEY_VALUE_PAIR Node = 24
	META_KEY_VALUE_SEQUENCE Node = 25
	META_SECTION Node = 26
	NEST_OR_EMBED Node = 27
	NodeCharLiteral Node = 28
	NodeDSLName Node = 29
	NodeExported Node = 30
	NodeHeader Node = 31
	NodeImportAlias Node = 32
	NodeImportDefinition Node = 33
	NodeImportEmbed Node = 34
	NodeImportKeyword Node = 35
	NodeImportPath Node = 36
	NodeImportSection Node = 37
	NodeLSPECName Node = 38
	NodeLexKeyword Node = 39
	NodeLexRule Node = 40
	NodeLexRulePattern Node = 41
	NodeLexRulePatternUsing Node = 42
	NodeLexRulePriority Node = 43
	NodeLexRuleRole Node = 44
	NodeLexRuleStateMutation Node = 45
	NodeLexRuleTokenName Node = 46
	NodeLexSection Node = 47
	NodeLocalVariable Node = 48
	NodeMetaKey Node = 49
	NodeMetaKeyValuePair Node = 50
	NodeMetaSection Node = 51
	NodeMetaValue Node = 52
	NodeModuleReference Node = 53
	NodeParseBlock Node = 54
	NodeParseEmbedStatement Node = 55
	NodeParseExpressionReference Node = 56
	NodeParseGroup Node = 57
	NodeParseIgnoreKeyword Node = 58
	NodeParseIgnoreRole Node = 59
	NodeParseIgnoreSection Node = 60
	NodeParseKeyword Node = 61
	NodeParseModifierPredict Node = 62
	NodeParseNestBody Node = 63
	NodeParseNestCloseToken Node = 64
	NodeParseNestOpenToken Node = 65
	NodeParseNestPairRef Node = 66
	NodeParseNodeName Node = 67
	NodeParseOpNest Node = 68
	NodeParseOpSuppress Node = 69
	NodeParsePair Node = 70
	NodeParsePairIdentifier Node = 71
	NodeParseRule Node = 72
	NodeParseRuleBody Node = 73
	NodeParseRuleName Node = 74
	NodeParseSection Node = 75
	NodeParseSectionBody Node = 76
	NodeParseSegment Node = 77
	NodeParseSymbolReference Node = 78
	NodeParseTemplate Node = 79
	NodeParseTemplateBody Node = 80
	NodeParseTemplateCallArgs Node = 81
	NodeParseTemplateCallArgument Node = 82
	NodeParseTemplateCallKeyword Node = 83
	NodeParseTemplateIdentifier Node = 84
	NodeParseTemplateParameter Node = 85
	NodeParseTemplateParameterIdentifier Node = 86
	NodeParseTemplateParameterList Node = 87
	NodeParseTemplateParameterReference Node = 88
	NodeParseTemplateParameterType Node = 89
	NodeParseTemplateReference Node = 90
	NodeParseTokenReference Node = 91
	NodePatternAny Node = 92
	NodePatternClass Node = 93
	NodePatternClassItem Node = 94
	NodePatternDefName Node = 95
	NodePatternDefinition Node = 96
	NodePatternExternalPatternReference Node = 97
	NodePatternGroup Node = 98
	NodePatternKeyword Node = 99
	NodePatternRange Node = 100
	NodePatternRef Node = 101
	NodePatternRegEx Node = 102
	NodePatternSection Node = 103
	NodePragmaBlock Node = 104
	NodePragmaBlockKey Node = 105
	NodePragmaBlockKeyPrefix Node = 106
	NodePragmaBlockKeySegment Node = 107
	NodePragmaConfiguration Node = 108
	NodePragmaKey Node = 109
	NodePragmaKeyword Node = 110
	NodePragmaSection Node = 111
	NodePragmaValue Node = 112
	NodePrattExprBody Node = 113
	NodePrattExprDef Node = 114
	NodePrattExprName Node = 115
	NodePrattImplicit Node = 116
	NodePrattImplicitBody Node = 117
	NodePrattImplicitDef Node = 118
	NodePrattInfix Node = 119
	NodePrattInfixBody Node = 120
	NodePrattKeyword Node = 121
	NodePrattLeftPrecedenceValue Node = 122
	NodePrattOperatorDef Node = 123
	NodePrattPostfix Node = 124
	NodePrattPostfixBody Node = 125
	NodePrattPrefix Node = 126
	NodePrattPrefixBody Node = 127
	NodePrattPrimary Node = 128
	NodePrattPrimaryBody Node = 129
	NodePrattPrimaryRef Node = 130
	NodePrattRightPrecedenceValue Node = 131
	NodePrattSection Node = 132
	NodePredictLookahead Node = 133
	NodePredictLookaheadList Node = 134
	NodePredictOffset Node = 135
	NodePredictToken Node = 136
	NodeProgram Node = 137
	NodeRepetitionBounds Node = 138
	NodeRepetitionMax Node = 139
	NodeRepetitionMin Node = 140
	NodeRuleModifierSync Node = 141
	NodeRuleModifierTransparent Node = 142
	NodeStateDefinition Node = 143
	NodeStateDefinitionBody Node = 144
	NodeStateDefinitionList Node = 145
	NodeStateKeyword Node = 146
	NodeStateList Node = 147
	NodeStateMutationArgumentList Node = 148
	NodeStateMutationPop Node = 149
	NodeStateMutationPopAmount Node = 150
	NodeStateMutationPush Node = 151
	NodeStateMutationSet Node = 152
	NodeStateReference Node = 153
	NodeStringArray Node = 154
	NodeStringLiteral Node = 155
	NodeSyncBlock Node = 156
	NodeSyncToken Node = 157
	NodeVersion Node = 158
	PARSE_BLOCK Node = 159
	PARSE_EMBED_STATEMENT_EMBED_NEST Node = 160
	PARSE_EXPRESSION_BP_10 Node = 161
	PARSE_EXPRESSION_BP_20 Node = 162
	PARSE_EXPRESSION_BP_30 Node = 163
	PARSE_EXPRESSION_BP_40 Node = 164
	PARSE_GROUP Node = 165
	PARSE_IGNORE_ROLE_LIST Node = 166
	PARSE_IGNORE_SECTION Node = 167
	PARSE_IGNORE_SECTION_BLOCK_NEST Node = 168
	PARSE_MODIFIER_PREDICT Node = 169
	PARSE_NEST_BODY Node = 170
	PARSE_OP_NEST_CHOICE Node = 171
	PARSE_OP_NEST_EXPLICIT Node = 172
	PARSE_OP_NEST_STANDARD_NEST Node = 173
	PARSE_OP_NEST_TPL_PARAM_DELIMS Node = 174
	PARSE_OP_SUPPRESS Node = 175
	PARSE_PAIR_DECLARATION Node = 176
	PARSE_RULE Node = 177
	PARSE_RULE_BODY Node = 178
	PARSE_SECTION Node = 179
	PARSE_SECTION_BLOCK_NEST Node = 180
	PARSE_SECTION_BODY Node = 181
	PARSE_SEGMENT Node = 182
	PARSE_SEGMENT_IDENT_MAPPING_OR_CALL Node = 183
	PARSE_SEGMENT_MAPPING_TAIL Node = 184
	PARSE_SEGMENT_MAPPING_TARGET_CHOICE Node = 185
	PARSE_SEGMENT_TEMPLATE_CALL_SEGMENT Node = 186
	PARSE_TEMPLATE_BODY Node = 187
	PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_SEGMENT Node = 188
	PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_LEX Node = 189
	PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_NEST Node = 190
	PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_PARSE_SEGMENT Node = 191
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_SEGMENT Node = 192
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_LEX Node = 193
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_NEST Node = 194
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_PARSE_SEGMENT Node = 195
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_SEGMENT Node = 196
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_LEX Node = 197
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_NEST Node = 198
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_PARSE_SEGMENT Node = 199
	PARSE_TEMPLATE_CALL_ARGS_SEGMENT Node = 200
	PARSE_TEMPLATE_CALL_ARGS_USING_LEX Node = 201
	PARSE_TEMPLATE_CALL_ARGS_USING_NEST Node = 202
	PARSE_TEMPLATE_CALL_ARGS_USING_PARSE_SEGMENT Node = 203
	PARSE_TEMPLATE_DECLARATION Node = 204
	PARSE_TEMPLATE_PARAMETER Node = 205
	PARSE_TEMPLATE_PARAMETER_LIST Node = 206
	PARSE_TEMPLATE_SIGNATURE Node = 207
	PATTERN_CLASS Node = 208
	PATTERN_CLASS_ITEM_COMMA Node = 209
	PATTERN_CLASS_ITEM_LIST Node = 210
	PATTERN_CLASS_ITEM_SEQ Node = 211
	PATTERN_DEFINITION Node = 212
	PATTERN_DEFINITION_LIST Node = 213
	PATTERN_EXPRESSION Node = 214
	PATTERN_EXPRESSION_BP_10 Node = 215
	PATTERN_EXPRESSION_BP_20 Node = 216
	PATTERN_EXPRESSION_BP_30 Node = 217
	PATTERN_EXPRESSION_BP_40 Node = 218
	PATTERN_EXPRESSION_BP_60 Node = 219
	PATTERN_GROUP Node = 220
	PATTERN_RANGE_TAIL Node = 221
	PATTERN_REF Node = 222
	PATTERN_SECTION Node = 223
	PATTERN_SECTION_BLOCK_NEST Node = 224
	PATTERN_SEGMENT Node = 225
	PRAGMA_BLOCK Node = 226
	PRAGMA_BLOCK_BLOCK_NEST Node = 227
	PRAGMA_BLOCK_KEY Node = 228
	PRAGMA_BLOCK_KEY_SEGMENT Node = 229
	PRAGMA_BLOCK_LIST Node = 230
	PRAGMA_CONFIGURATION Node = 231
	PRAGMA_CONFIGURATION_LIST Node = 232
	PRAGMA_SECTION Node = 233
	PRAGMA_SECTION_BLOCK_NEST Node = 234
	PRAGMA_VALUE Node = 235
	PRATT_CATEGORY Node = 236
	PRATT_CATEGORY_LIST Node = 237
	PRATT_EXPR_BODY Node = 238
	PRATT_EXPR_DEF Node = 239
	PRATT_EXPR_DEF_LIST Node = 240
	PRATT_IMPLICIT Node = 241
	PRATT_IMPLICIT_BODY Node = 242
	PRATT_IMPLICIT_DEF Node = 243
	PRATT_INFIX Node = 244
	PRATT_INFIX_BODY Node = 245
	PRATT_INFIX_LIST Node = 246
	PRATT_OPERATOR_DEF_INFIX Node = 247
	PRATT_OPERATOR_DEF_POSTFIX Node = 248
	PRATT_OPERATOR_DEF_PREFIX Node = 249
	PRATT_POSTFIX Node = 250
	PRATT_POSTFIX_BODY Node = 251
	PRATT_POSTFIX_LIST Node = 252
	PRATT_PREFIX Node = 253
	PRATT_PREFIX_BODY Node = 254
	PRATT_PREFIX_LIST Node = 255
	PRATT_PRIMARY Node = 256
	PRATT_PRIMARY_BODY Node = 257
	PRATT_PRIMARY_REF Node = 258
	PRATT_SECTION Node = 259
	PRATT_SECTION_BLOCK_NEST Node = 260
	PREDICT_LOOKAHEAD Node = 261
	PREDICT_LOOKAHEAD_ITEMS Node = 262
	PREDICT_LOOKAHEAD_LIST Node = 263
	PREFIX_DUMMY_RULE_PATTERNS Node = 264
	REPETITION_BOUNDS Node = 265
	REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ Node = 266
	REPETITION_BOUNDS_NEST Node = 267
	REPETITION_BOUNDS_STARTS_WITH_COMMA Node = 268
	REPETITION_BOUNDS_STARTS_WITH_MIN Node = 269
	RULE_MODIFIER_SYNC Node = 270
	STATE_DEFINITION_BODY Node = 271
	STATE_DEFINITION_LIST Node = 272
	STATE_DEFINITION_TAIL Node = 273
	STATE_DEFINITION_TAIL_CONTENT Node = 274
	STATE_LIST Node = 275
	STATE_LIST_BLOCKS Node = 276
	STATE_MUTATION_ARGUMENT_LIST_ARGS Node = 277
	STATE_MUTATION_ARGUMENT_LIST_LIST Node = 278
	STATE_MUTATION_ARGUMENT_LIST_POP Node = 279
	STATE_MUTATION_ARGUMENT_LIST_TAIL Node = 280
	STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT Node = 281
	STATE_MUTATION_POP Node = 282
	STATE_MUTATION_PUSH Node = 283
	STATE_MUTATION_SET Node = 284
	STRING_ARRAY Node = 285
	STRING_ARRAY_ELEMENT_LIST Node = 286
	STRING_ARRAY_ELEMENT_LIST_TAIL Node = 287
	STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT Node = 288
	SYNC_BLOCK Node = 289
	SYNC_TOKEN_LIST Node = 290
	TEMPLATE_ARGUMENT_LIST_TAIL Node = 291
	TEMPLATE_ARGUMENT_LIST_TAIL_CONTENT Node = 292
	gr_DUMMY_CHOICE_FOR_PRAGMA_VALUES Node = 293
	gr_DUMMY_CHOICE_IDENT_MAP_BASE Node = 294
	gr_DUMMY_CHOICE_NEST Node = 295
	gr_DUMMY_CHOICE_PARSE_BLOCK_CHOICE Node = 296
	gr_DUMMY_CHOICE_PARSE_BLOCK_LIST Node = 297
	gr_DUMMY_CHOICE_VIRTUAL_MAPPING Node = 298
	gr_HEADER Node = 299
	gr_IMPORT_DEFINITION_LIST Node = 300
	gr_IMPORT_SECTION_BLOCK_NEST Node = 301
	gr_LEX_RULE_LIST Node = 302
	gr_LEX_RULE_PATTERN Node = 303
	gr_LEX_RULE_STATE_MUTATION_KIND Node = 304
	gr_LEX_SECTION_BLOCK_NEST Node = 305
	gr_META_KEY_VALUE_PAIR Node = 306
	gr_NEST_OR_EMBED Node = 307
	gr_NodePatternRef Node = 308
	gr_PARSE_EXPRESSION Node = 309
	gr_PARSE_EXPRESSION_BP_10 Node = 310
	gr_PARSE_EXPRESSION_BP_20 Node = 311
	gr_PARSE_EXPRESSION_BP_30 Node = 312
	gr_PARSE_EXPRESSION_BP_40 Node = 313
	gr_PARSE_IGNORE_ROLE_LIST Node = 314
	gr_PARSE_IGNORE_SECTION_BLOCK_NEST Node = 315
	gr_PARSE_OP_NEST_CHOICE Node = 316
	gr_PARSE_OP_NEST_EXPLICIT Node = 317
	gr_PARSE_OP_NEST_TPL_PARAM_DELIMS Node = 318
	gr_PARSE_SECTION_BLOCK_NEST Node = 319
	gr_PARSE_SEGMENT Node = 320
	gr_PARSE_SEGMENT_MAPPING_TARGET_CHOICE Node = 321
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_SEGMENT Node = 322
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_LEX Node = 323
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_NEST Node = 324
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_PARSE_SEGMENT Node = 325
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_SEGMENT Node = 326
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_LEX Node = 327
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_NEST Node = 328
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_PARSE_SEGMENT Node = 329
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_SEGMENT Node = 330
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_LEX Node = 331
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_NEST Node = 332
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_PARSE_SEGMENT Node = 333
	gr_PARSE_TEMPLATE_SIGNATURE Node = 334
	gr_PATTERN_CLASS_ITEM_LIST Node = 335
	gr_PATTERN_DEFINITION_LIST Node = 336
	gr_PATTERN_EXPRESSION Node = 337
	gr_PATTERN_EXPRESSION_BP_10 Node = 338
	gr_PATTERN_EXPRESSION_BP_20 Node = 339
	gr_PATTERN_EXPRESSION_BP_30 Node = 340
	gr_PATTERN_EXPRESSION_BP_40 Node = 341
	gr_PATTERN_EXPRESSION_BP_60 Node = 342
	gr_PATTERN_SECTION_BLOCK_NEST Node = 343
	gr_PATTERN_SEGMENT Node = 344
	gr_PRAGMA_BLOCK_BLOCK_NEST Node = 345
	gr_PRAGMA_BLOCK_LIST Node = 346
	gr_PRAGMA_CONFIGURATION_LIST Node = 347
	gr_PRAGMA_SECTION_BLOCK_NEST Node = 348
	gr_PRATT_CATEGORY Node = 349
	gr_PRATT_CATEGORY_LIST Node = 350
	gr_PRATT_EXPR_DEF_LIST Node = 351
	gr_PRATT_INFIX_LIST Node = 352
	gr_PRATT_POSTFIX_LIST Node = 353
	gr_PRATT_PREFIX_LIST Node = 354
	gr_PRATT_SECTION_BLOCK_NEST Node = 355
	gr_PREDICT_LOOKAHEAD_ITEMS Node = 356
	gr_PREFIX_DUMMY_RULE_PATTERNS Node = 357
	gr_REPETITION_BOUNDS Node = 358
	gr_REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ Node = 359
	gr_REPETITION_BOUNDS_NEST Node = 360
	gr_STATE_DEFINITION_TAIL Node = 361
	gr_STATE_DEFINITION_TAIL_CONTENT Node = 362
	gr_STATE_LIST_BLOCKS Node = 363
	gr_STATE_MUTATION_ARGUMENT_LIST_TAIL Node = 364
	gr_STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT Node = 365
	gr_STRING_ARRAY_ELEMENT_LIST Node = 366
	gr_STRING_ARRAY_ELEMENT_LIST_TAIL Node = 367
	gr_STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT Node = 368
	gr_SYNC_TOKEN_LIST Node = 369
	gr_TEMPLATE_ARGUMENT_LIST_TAIL Node = 370
	gr_TEMPLATE_ARGUMENT_LIST_TAIL_CONTENT Node = 371
)

var NodeNames = [...]string{
	"DUMMY_CHOICE_FOR_PRAGMA_VALUES",
	"DUMMY_CHOICE_IDENT_MAP_BASE",
	"DUMMY_CHOICE_NEST",
	"DUMMY_CHOICE_PARSE_BLOCK_CHOICE",
	"DUMMY_CHOICE_PARSE_BLOCK_LIST",
	"DUMMY_CHOICE_VIRTUAL_MAPPING",
	"ERROR_NODE",
	"HEADER",
	"HEADER_CONTENT",
	"IMPORT_DEFINITION",
	"IMPORT_DEFINITION_LIST",
	"IMPORT_SECTION",
	"IMPORT_SECTION_BLOCK_NEST",
	"LEX_RULE",
	"LEX_RULE_LIST",
	"LEX_RULE_PATTERN",
	"LEX_RULE_PATTERN_USING_LEX",
	"LEX_RULE_PATTERN_USING_NEST",
	"LEX_RULE_PATTERN_USING_PARSE_SEGMENT",
	"LEX_RULE_STATE_MUTATION",
	"LEX_RULE_STATE_MUTATION_KIND",
	"LEX_SECTION",
	"LEX_SECTION_BLOCK_NEST",
	"META_KEY_VALUE_PAIR",
	"META_KEY_VALUE_SEQUENCE",
	"META_SECTION",
	"NEST_OR_EMBED",
	"NodeCharLiteral",
	"NodeDSLName",
	"NodeExported",
	"NodeHeader",
	"NodeImportAlias",
	"NodeImportDefinition",
	"NodeImportEmbed",
	"NodeImportKeyword",
	"NodeImportPath",
	"NodeImportSection",
	"NodeLSPECName",
	"NodeLexKeyword",
	"NodeLexRule",
	"NodeLexRulePattern",
	"NodeLexRulePatternUsing",
	"NodeLexRulePriority",
	"NodeLexRuleRole",
	"NodeLexRuleStateMutation",
	"NodeLexRuleTokenName",
	"NodeLexSection",
	"NodeLocalVariable",
	"NodeMetaKey",
	"NodeMetaKeyValuePair",
	"NodeMetaSection",
	"NodeMetaValue",
	"NodeModuleReference",
	"NodeParseBlock",
	"NodeParseEmbedStatement",
	"NodeParseExpressionReference",
	"NodeParseGroup",
	"NodeParseIgnoreKeyword",
	"NodeParseIgnoreRole",
	"NodeParseIgnoreSection",
	"NodeParseKeyword",
	"NodeParseModifierPredict",
	"NodeParseNestBody",
	"NodeParseNestCloseToken",
	"NodeParseNestOpenToken",
	"NodeParseNestPairRef",
	"NodeParseNodeName",
	"NodeParseOpNest",
	"NodeParseOpSuppress",
	"NodeParsePair",
	"NodeParsePairIdentifier",
	"NodeParseRule",
	"NodeParseRuleBody",
	"NodeParseRuleName",
	"NodeParseSection",
	"NodeParseSectionBody",
	"NodeParseSegment",
	"NodeParseSymbolReference",
	"NodeParseTemplate",
	"NodeParseTemplateBody",
	"NodeParseTemplateCallArgs",
	"NodeParseTemplateCallArgument",
	"NodeParseTemplateCallKeyword",
	"NodeParseTemplateIdentifier",
	"NodeParseTemplateParameter",
	"NodeParseTemplateParameterIdentifier",
	"NodeParseTemplateParameterList",
	"NodeParseTemplateParameterReference",
	"NodeParseTemplateParameterType",
	"NodeParseTemplateReference",
	"NodeParseTokenReference",
	"NodePatternAny",
	"NodePatternClass",
	"NodePatternClassItem",
	"NodePatternDefName",
	"NodePatternDefinition",
	"NodePatternExternalPatternReference",
	"NodePatternGroup",
	"NodePatternKeyword",
	"NodePatternRange",
	"NodePatternRef",
	"NodePatternRegEx",
	"NodePatternSection",
	"NodePragmaBlock",
	"NodePragmaBlockKey",
	"NodePragmaBlockKeyPrefix",
	"NodePragmaBlockKeySegment",
	"NodePragmaConfiguration",
	"NodePragmaKey",
	"NodePragmaKeyword",
	"NodePragmaSection",
	"NodePragmaValue",
	"NodePrattExprBody",
	"NodePrattExprDef",
	"NodePrattExprName",
	"NodePrattImplicit",
	"NodePrattImplicitBody",
	"NodePrattImplicitDef",
	"NodePrattInfix",
	"NodePrattInfixBody",
	"NodePrattKeyword",
	"NodePrattLeftPrecedenceValue",
	"NodePrattOperatorDef",
	"NodePrattPostfix",
	"NodePrattPostfixBody",
	"NodePrattPrefix",
	"NodePrattPrefixBody",
	"NodePrattPrimary",
	"NodePrattPrimaryBody",
	"NodePrattPrimaryRef",
	"NodePrattRightPrecedenceValue",
	"NodePrattSection",
	"NodePredictLookahead",
	"NodePredictLookaheadList",
	"NodePredictOffset",
	"NodePredictToken",
	"NodeProgram",
	"NodeRepetitionBounds",
	"NodeRepetitionMax",
	"NodeRepetitionMin",
	"NodeRuleModifierSync",
	"NodeRuleModifierTransparent",
	"NodeStateDefinition",
	"NodeStateDefinitionBody",
	"NodeStateDefinitionList",
	"NodeStateKeyword",
	"NodeStateList",
	"NodeStateMutationArgumentList",
	"NodeStateMutationPop",
	"NodeStateMutationPopAmount",
	"NodeStateMutationPush",
	"NodeStateMutationSet",
	"NodeStateReference",
	"NodeStringArray",
	"NodeStringLiteral",
	"NodeSyncBlock",
	"NodeSyncToken",
	"NodeVersion",
	"PARSE_BLOCK",
	"PARSE_EMBED_STATEMENT_EMBED_NEST",
	"PARSE_EXPRESSION_BP_10",
	"PARSE_EXPRESSION_BP_20",
	"PARSE_EXPRESSION_BP_30",
	"PARSE_EXPRESSION_BP_40",
	"PARSE_GROUP",
	"PARSE_IGNORE_ROLE_LIST",
	"PARSE_IGNORE_SECTION",
	"PARSE_IGNORE_SECTION_BLOCK_NEST",
	"PARSE_MODIFIER_PREDICT",
	"PARSE_NEST_BODY",
	"PARSE_OP_NEST_CHOICE",
	"PARSE_OP_NEST_EXPLICIT",
	"PARSE_OP_NEST_STANDARD_NEST",
	"PARSE_OP_NEST_TPL_PARAM_DELIMS",
	"PARSE_OP_SUPPRESS",
	"PARSE_PAIR_DECLARATION",
	"PARSE_RULE",
	"PARSE_RULE_BODY",
	"PARSE_SECTION",
	"PARSE_SECTION_BLOCK_NEST",
	"PARSE_SECTION_BODY",
	"PARSE_SEGMENT",
	"PARSE_SEGMENT_IDENT_MAPPING_OR_CALL",
	"PARSE_SEGMENT_MAPPING_TAIL",
	"PARSE_SEGMENT_MAPPING_TARGET_CHOICE",
	"PARSE_SEGMENT_TEMPLATE_CALL_SEGMENT",
	"PARSE_TEMPLATE_BODY",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_LEX",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_NEST",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_PARSE_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_LEX",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_NEST",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_PARSE_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_LEX",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_NEST",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_PARSE_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_USING_LEX",
	"PARSE_TEMPLATE_CALL_ARGS_USING_NEST",
	"PARSE_TEMPLATE_CALL_ARGS_USING_PARSE_SEGMENT",
	"PARSE_TEMPLATE_DECLARATION",
	"PARSE_TEMPLATE_PARAMETER",
	"PARSE_TEMPLATE_PARAMETER_LIST",
	"PARSE_TEMPLATE_SIGNATURE",
	"PATTERN_CLASS",
	"PATTERN_CLASS_ITEM_COMMA",
	"PATTERN_CLASS_ITEM_LIST",
	"PATTERN_CLASS_ITEM_SEQ",
	"PATTERN_DEFINITION",
	"PATTERN_DEFINITION_LIST",
	"PATTERN_EXPRESSION",
	"PATTERN_EXPRESSION_BP_10",
	"PATTERN_EXPRESSION_BP_20",
	"PATTERN_EXPRESSION_BP_30",
	"PATTERN_EXPRESSION_BP_40",
	"PATTERN_EXPRESSION_BP_60",
	"PATTERN_GROUP",
	"PATTERN_RANGE_TAIL",
	"PATTERN_REF",
	"PATTERN_SECTION",
	"PATTERN_SECTION_BLOCK_NEST",
	"PATTERN_SEGMENT",
	"PRAGMA_BLOCK",
	"PRAGMA_BLOCK_BLOCK_NEST",
	"PRAGMA_BLOCK_KEY",
	"PRAGMA_BLOCK_KEY_SEGMENT",
	"PRAGMA_BLOCK_LIST",
	"PRAGMA_CONFIGURATION",
	"PRAGMA_CONFIGURATION_LIST",
	"PRAGMA_SECTION",
	"PRAGMA_SECTION_BLOCK_NEST",
	"PRAGMA_VALUE",
	"PRATT_CATEGORY",
	"PRATT_CATEGORY_LIST",
	"PRATT_EXPR_BODY",
	"PRATT_EXPR_DEF",
	"PRATT_EXPR_DEF_LIST",
	"PRATT_IMPLICIT",
	"PRATT_IMPLICIT_BODY",
	"PRATT_IMPLICIT_DEF",
	"PRATT_INFIX",
	"PRATT_INFIX_BODY",
	"PRATT_INFIX_LIST",
	"PRATT_OPERATOR_DEF_INFIX",
	"PRATT_OPERATOR_DEF_POSTFIX",
	"PRATT_OPERATOR_DEF_PREFIX",
	"PRATT_POSTFIX",
	"PRATT_POSTFIX_BODY",
	"PRATT_POSTFIX_LIST",
	"PRATT_PREFIX",
	"PRATT_PREFIX_BODY",
	"PRATT_PREFIX_LIST",
	"PRATT_PRIMARY",
	"PRATT_PRIMARY_BODY",
	"PRATT_PRIMARY_REF",
	"PRATT_SECTION",
	"PRATT_SECTION_BLOCK_NEST",
	"PREDICT_LOOKAHEAD",
	"PREDICT_LOOKAHEAD_ITEMS",
	"PREDICT_LOOKAHEAD_LIST",
	"PREFIX_DUMMY_RULE_PATTERNS",
	"REPETITION_BOUNDS",
	"REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ",
	"REPETITION_BOUNDS_NEST",
	"REPETITION_BOUNDS_STARTS_WITH_COMMA",
	"REPETITION_BOUNDS_STARTS_WITH_MIN",
	"RULE_MODIFIER_SYNC",
	"STATE_DEFINITION_BODY",
	"STATE_DEFINITION_LIST",
	"STATE_DEFINITION_TAIL",
	"STATE_DEFINITION_TAIL_CONTENT",
	"STATE_LIST",
	"STATE_LIST_BLOCKS",
	"STATE_MUTATION_ARGUMENT_LIST_ARGS",
	"STATE_MUTATION_ARGUMENT_LIST_LIST",
	"STATE_MUTATION_ARGUMENT_LIST_POP",
	"STATE_MUTATION_ARGUMENT_LIST_TAIL",
	"STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT",
	"STATE_MUTATION_POP",
	"STATE_MUTATION_PUSH",
	"STATE_MUTATION_SET",
	"STRING_ARRAY",
	"STRING_ARRAY_ELEMENT_LIST",
	"STRING_ARRAY_ELEMENT_LIST_TAIL",
	"STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT",
	"SYNC_BLOCK",
	"SYNC_TOKEN_LIST",
	"TEMPLATE_ARGUMENT_LIST_TAIL",
	"TEMPLATE_ARGUMENT_LIST_TAIL_CONTENT",
	"gr_DUMMY_CHOICE_FOR_PRAGMA_VALUES",
	"gr_DUMMY_CHOICE_IDENT_MAP_BASE",
	"gr_DUMMY_CHOICE_NEST",
	"gr_DUMMY_CHOICE_PARSE_BLOCK_CHOICE",
	"gr_DUMMY_CHOICE_PARSE_BLOCK_LIST",
	"gr_DUMMY_CHOICE_VIRTUAL_MAPPING",
	"gr_HEADER",
	"gr_IMPORT_DEFINITION_LIST",
	"gr_IMPORT_SECTION_BLOCK_NEST",
	"gr_LEX_RULE_LIST",
	"gr_LEX_RULE_PATTERN",
	"gr_LEX_RULE_STATE_MUTATION_KIND",
	"gr_LEX_SECTION_BLOCK_NEST",
	"gr_META_KEY_VALUE_PAIR",
	"gr_NEST_OR_EMBED",
	"gr_NodePatternRef",
	"gr_PARSE_EXPRESSION",
	"gr_PARSE_EXPRESSION_BP_10",
	"gr_PARSE_EXPRESSION_BP_20",
	"gr_PARSE_EXPRESSION_BP_30",
	"gr_PARSE_EXPRESSION_BP_40",
	"gr_PARSE_IGNORE_ROLE_LIST",
	"gr_PARSE_IGNORE_SECTION_BLOCK_NEST",
	"gr_PARSE_OP_NEST_CHOICE",
	"gr_PARSE_OP_NEST_EXPLICIT",
	"gr_PARSE_OP_NEST_TPL_PARAM_DELIMS",
	"gr_PARSE_SECTION_BLOCK_NEST",
	"gr_PARSE_SEGMENT",
	"gr_PARSE_SEGMENT_MAPPING_TARGET_CHOICE",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_SEGMENT",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_LEX",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_NEST",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_PARSE_SEGMENT",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_SEGMENT",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_LEX",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_NEST",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_PARSE_SEGMENT",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_SEGMENT",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_LEX",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_NEST",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_PARSE_SEGMENT",
	"gr_PARSE_TEMPLATE_SIGNATURE",
	"gr_PATTERN_CLASS_ITEM_LIST",
	"gr_PATTERN_DEFINITION_LIST",
	"gr_PATTERN_EXPRESSION",
	"gr_PATTERN_EXPRESSION_BP_10",
	"gr_PATTERN_EXPRESSION_BP_20",
	"gr_PATTERN_EXPRESSION_BP_30",
	"gr_PATTERN_EXPRESSION_BP_40",
	"gr_PATTERN_EXPRESSION_BP_60",
	"gr_PATTERN_SECTION_BLOCK_NEST",
	"gr_PATTERN_SEGMENT",
	"gr_PRAGMA_BLOCK_BLOCK_NEST",
	"gr_PRAGMA_BLOCK_LIST",
	"gr_PRAGMA_CONFIGURATION_LIST",
	"gr_PRAGMA_SECTION_BLOCK_NEST",
	"gr_PRATT_CATEGORY",
	"gr_PRATT_CATEGORY_LIST",
	"gr_PRATT_EXPR_DEF_LIST",
	"gr_PRATT_INFIX_LIST",
	"gr_PRATT_POSTFIX_LIST",
	"gr_PRATT_PREFIX_LIST",
	"gr_PRATT_SECTION_BLOCK_NEST",
	"gr_PREDICT_LOOKAHEAD_ITEMS",
	"gr_PREFIX_DUMMY_RULE_PATTERNS",
	"gr_REPETITION_BOUNDS",
	"gr_REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ",
	"gr_REPETITION_BOUNDS_NEST",
	"gr_STATE_DEFINITION_TAIL",
	"gr_STATE_DEFINITION_TAIL_CONTENT",
	"gr_STATE_LIST_BLOCKS",
	"gr_STATE_MUTATION_ARGUMENT_LIST_TAIL",
	"gr_STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT",
	"gr_STRING_ARRAY_ELEMENT_LIST",
	"gr_STRING_ARRAY_ELEMENT_LIST_TAIL",
	"gr_STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT",
	"gr_SYNC_TOKEN_LIST",
	"gr_TEMPLATE_ARGUMENT_LIST_TAIL",
	"gr_TEMPLATE_ARGUMENT_LIST_TAIL_CONTENT",
}

func (t Node) String() string {
	if t < 1 || int(t-1) >= len(NodeNames) {
		return "Node(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return NodeNames[t-1]
}
