// Code generated by LangSpec. DO NOT EDIT.

package compiler

import (
	"lexarch"
	"strconv"
)

// Token represents a Token generated by LangSpec (IDs match compiler symbol table).
type Token = lexarch.TokenKind

const (
	TokBlockComment Token = 2
	TokBraceClose Token = 3
	TokBraceOpen Token = 4
	TokBracketClose Token = 5
	TokBracketOpen Token = 6
	TokChainSeparator Token = 7
	TokCharLiteral Token = 8
	TokColon Token = 9
	TokComma Token = 10
	TokDashes Token = 11
	TokDot Token = 12
	TokEOF Token = 13
	TokEqualsOperator Token = 14
	TokIdentifier Token = 15
	TokInteger Token = 16
	TokKWAs Token = 17
	TokKWCall Token = 18
	TokKWExport Token = 19
	TokKWFalse Token = 20
	TokKWIgnore Token = 21
	TokKWImplicit Token = 22
	TokKWImport Token = 23
	TokKWInfix Token = 24
	TokKWLSpec Token = 25
	TokKWLex Token = 26
	TokKWLocal Token = 27
	TokKWNest Token = 28
	TokKWPair Token = 29
	TokKWParse Token = 30
	TokKWPattern Token = 31
	TokKWPop Token = 32
	TokKWPostfix Token = 33
	TokKWPragma Token = 34
	TokKWPratt Token = 35
	TokKWPrecedence Token = 36
	TokKWPredict Token = 37
	TokKWPrefix Token = 38
	TokKWPrimary Token = 39
	TokKWPush Token = 40
	TokKWRule Token = 41
	TokKWSet Token = 42
	TokKWState Token = 43
	TokKWSync Token = 44
	TokKWTemplate Token = 45
	TokKWTool Token = 46
	TokKWTransparent Token = 47
	TokKWTrue Token = 48
	TokKWUsing Token = 49
	TokKWVirtual Token = 50
	TokLineComment Token = 51
	TokMetaSection Token = 52
	TokNegation Token = 53
	TokOptional Token = 54
	TokPairReference Token = 55
	TokParameter Token = 56
	TokParenClose Token = 57
	TokParenOpen Token = 58
	TokPipe Token = 59
	TokPlus Token = 60
	TokRange Token = 61
	TokRegexLiteral Token = 62
	TokSemicolon Token = 63
	TokStar Token = 64
	TokStringLiteral Token = 65
	TokTypeNode Token = 66
	TokTypePair Token = 67
	TokTypePrattExpr Token = 68
	TokTypeRule Token = 69
	TokTypeToken Token = 70
	TokVersion Token = 71
	TokWhitespace Token = 72
)

var TokenNames = [...]string{
	"TokBlockComment",
	"TokBraceClose",
	"TokBraceOpen",
	"TokBracketClose",
	"TokBracketOpen",
	"TokChainSeparator",
	"TokCharLiteral",
	"TokColon",
	"TokComma",
	"TokDashes",
	"TokDot",
	"TokEOF",
	"TokEqualsOperator",
	"TokIdentifier",
	"TokInteger",
	"TokKWAs",
	"TokKWCall",
	"TokKWExport",
	"TokKWFalse",
	"TokKWIgnore",
	"TokKWImplicit",
	"TokKWImport",
	"TokKWInfix",
	"TokKWLSpec",
	"TokKWLex",
	"TokKWLocal",
	"TokKWNest",
	"TokKWPair",
	"TokKWParse",
	"TokKWPattern",
	"TokKWPop",
	"TokKWPostfix",
	"TokKWPragma",
	"TokKWPratt",
	"TokKWPrecedence",
	"TokKWPredict",
	"TokKWPrefix",
	"TokKWPrimary",
	"TokKWPush",
	"TokKWRule",
	"TokKWSet",
	"TokKWState",
	"TokKWSync",
	"TokKWTemplate",
	"TokKWTool",
	"TokKWTransparent",
	"TokKWTrue",
	"TokKWUsing",
	"TokKWVirtual",
	"TokLineComment",
	"TokMetaSection",
	"TokNegation",
	"TokOptional",
	"TokPairReference",
	"TokParameter",
	"TokParenClose",
	"TokParenOpen",
	"TokPipe",
	"TokPlus",
	"TokRange",
	"TokRegexLiteral",
	"TokSemicolon",
	"TokStar",
	"TokStringLiteral",
	"TokTypeNode",
	"TokTypePair",
	"TokTypePrattExpr",
	"TokTypeRule",
	"TokTypeToken",
	"TokVersion",
	"TokWhitespace",
}

func TokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "Token(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return TokenNames[t-2]
}

func TokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "", false
	}
	return TokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(TokenTokenKindStringResolver)
}

// Node represents a Node generated by LangSpec (IDs match compiler symbol table).
type Node uint32

const (
	DUMMY_CHOICE_FOR_PRAGMA_VALUES Node = 1
	DUMMY_CHOICE_IDENT_MAP_BASE Node = 2
	DUMMY_CHOICE_NEST Node = 3
	DUMMY_CHOICE_PARSE_BLOCK_CHOICE Node = 4
	DUMMY_CHOICE_PARSE_BLOCK_LIST Node = 5
	DUMMY_CHOICE_VIRTUAL_MAPPING Node = 6
	ERROR_NODE Node = 7
	HEADER Node = 8
	HEADER_CONTENT Node = 9
	IMPORT_DEFINITION Node = 10
	IMPORT_DEFINITION_LIST Node = 11
	IMPORT_SECTION Node = 12
	IMPORT_SECTION_BLOCK_NEST Node = 13
	LEX_RULE Node = 14
	LEX_RULE_LIST Node = 15
	LEX_RULE_PATTERN Node = 16
	LEX_RULE_PATTERN_USING_LEX Node = 17
	LEX_RULE_PATTERN_USING_NEST Node = 18
	LEX_RULE_PATTERN_USING_PARSE_SEGMENT Node = 19
	LEX_RULE_STATE_MUTATION Node = 20
	LEX_RULE_STATE_MUTATION_KIND Node = 21
	LEX_SECTION Node = 22
	LEX_SECTION_BLOCK_NEST Node = 23
	META_KEY_VALUE_PAIR Node = 24
	META_KEY_VALUE_SEQUENCE Node = 25
	META_SECTION Node = 26
	NodeCharLiteral Node = 27
	NodeDSLName Node = 28
	NodeExported Node = 29
	NodeHeader Node = 30
	NodeImportAlias Node = 31
	NodeImportDefinition Node = 32
	NodeImportKeyword Node = 33
	NodeImportPath Node = 34
	NodeImportSection Node = 35
	NodeLSPECName Node = 36
	NodeLexKeyword Node = 37
	NodeLexRule Node = 38
	NodeLexRulePattern Node = 39
	NodeLexRulePatternUsing Node = 40
	NodeLexRulePriority Node = 41
	NodeLexRuleRole Node = 42
	NodeLexRuleStateMutation Node = 43
	NodeLexRuleTokenName Node = 44
	NodeLexSection Node = 45
	NodeLocalVariable Node = 46
	NodeMetaKey Node = 47
	NodeMetaKeyValuePair Node = 48
	NodeMetaSection Node = 49
	NodeMetaValue Node = 50
	NodeModuleReference Node = 51
	NodeParseBlock Node = 52
	NodeParseExpressionReference Node = 53
	NodeParseGroup Node = 54
	NodeParseIgnoreKeyword Node = 55
	NodeParseIgnoreRole Node = 56
	NodeParseIgnoreSection Node = 57
	NodeParseKeyword Node = 58
	NodeParseModifierPredict Node = 59
	NodeParseNestBody Node = 60
	NodeParseNestCloseToken Node = 61
	NodeParseNestOpenToken Node = 62
	NodeParseNestPairRef Node = 63
	NodeParseNodeName Node = 64
	NodeParseOpNest Node = 65
	NodeParseOpSuppress Node = 66
	NodeParsePair Node = 67
	NodeParsePairIdentifier Node = 68
	NodeParseRule Node = 69
	NodeParseRuleBody Node = 70
	NodeParseRuleName Node = 71
	NodeParseSection Node = 72
	NodeParseSectionBody Node = 73
	NodeParseSegment Node = 74
	NodeParseSymbolReference Node = 75
	NodeParseTemplate Node = 76
	NodeParseTemplateBody Node = 77
	NodeParseTemplateCallArgs Node = 78
	NodeParseTemplateCallArgument Node = 79
	NodeParseTemplateCallKeyword Node = 80
	NodeParseTemplateIdentifier Node = 81
	NodeParseTemplateParameter Node = 82
	NodeParseTemplateParameterIdentifier Node = 83
	NodeParseTemplateParameterList Node = 84
	NodeParseTemplateParameterReference Node = 85
	NodeParseTemplateParameterType Node = 86
	NodeParseTemplateReference Node = 87
	NodeParseTokenReference Node = 88
	NodePatternAny Node = 89
	NodePatternClass Node = 90
	NodePatternClassItem Node = 91
	NodePatternDefName Node = 92
	NodePatternDefinition Node = 93
	NodePatternExternalPatternReference Node = 94
	NodePatternGroup Node = 95
	NodePatternKeyword Node = 96
	NodePatternRange Node = 97
	NodePatternRef Node = 98
	NodePatternRegEx Node = 99
	NodePatternSection Node = 100
	NodePragmaBlock Node = 101
	NodePragmaBlockKey Node = 102
	NodePragmaBlockKeyPrefix Node = 103
	NodePragmaBlockKeySegment Node = 104
	NodePragmaConfiguration Node = 105
	NodePragmaKey Node = 106
	NodePragmaKeyword Node = 107
	NodePragmaSection Node = 108
	NodePragmaValue Node = 109
	NodePrattExprBody Node = 110
	NodePrattExprDef Node = 111
	NodePrattExprName Node = 112
	NodePrattImplicit Node = 113
	NodePrattImplicitBody Node = 114
	NodePrattImplicitDef Node = 115
	NodePrattInfix Node = 116
	NodePrattInfixBody Node = 117
	NodePrattKeyword Node = 118
	NodePrattLeftPrecedenceValue Node = 119
	NodePrattOperatorDef Node = 120
	NodePrattPostfix Node = 121
	NodePrattPostfixBody Node = 122
	NodePrattPrefix Node = 123
	NodePrattPrefixBody Node = 124
	NodePrattPrimary Node = 125
	NodePrattPrimaryBody Node = 126
	NodePrattPrimaryRef Node = 127
	NodePrattRightPrecedenceValue Node = 128
	NodePrattSection Node = 129
	NodePredictLookahead Node = 130
	NodePredictLookaheadList Node = 131
	NodePredictOffset Node = 132
	NodePredictToken Node = 133
	NodeProgram Node = 134
	NodeRepetitionBounds Node = 135
	NodeRepetitionMax Node = 136
	NodeRepetitionMin Node = 137
	NodeRuleModifierSync Node = 138
	NodeRuleModifierTransparent Node = 139
	NodeStateDefinition Node = 140
	NodeStateDefinitionBody Node = 141
	NodeStateDefinitionList Node = 142
	NodeStateKeyword Node = 143
	NodeStateList Node = 144
	NodeStateMutationArgumentList Node = 145
	NodeStateMutationPop Node = 146
	NodeStateMutationPopAmount Node = 147
	NodeStateMutationPush Node = 148
	NodeStateMutationSet Node = 149
	NodeStateReference Node = 150
	NodeStringArray Node = 151
	NodeStringLiteral Node = 152
	NodeSyncBlock Node = 153
	NodeSyncToken Node = 154
	NodeVersion Node = 155
	PARSE_BLOCK Node = 156
	PARSE_EXPRESSION_BP_10 Node = 157
	PARSE_EXPRESSION_BP_20 Node = 158
	PARSE_EXPRESSION_BP_30 Node = 159
	PARSE_EXPRESSION_BP_40 Node = 160
	PARSE_GROUP Node = 161
	PARSE_IGNORE_ROLE_LIST Node = 162
	PARSE_IGNORE_SECTION Node = 163
	PARSE_IGNORE_SECTION_BLOCK_NEST Node = 164
	PARSE_MODIFIER_PREDICT Node = 165
	PARSE_NEST_BODY Node = 166
	PARSE_OP_NEST Node = 167
	PARSE_OP_NEST_CHOICE Node = 168
	PARSE_OP_NEST_EXPLICIT Node = 169
	PARSE_OP_SUPPRESS Node = 170
	PARSE_PAIR_DECLARATION Node = 171
	PARSE_RULE Node = 172
	PARSE_RULE_BODY Node = 173
	PARSE_SECTION Node = 174
	PARSE_SECTION_BLOCK_NEST Node = 175
	PARSE_SECTION_BODY Node = 176
	PARSE_SEGMENT Node = 177
	PARSE_SEGMENT_IDENT_MAPPING_OR_CALL Node = 178
	PARSE_SEGMENT_MAPPING_TAIL Node = 179
	PARSE_SEGMENT_MAPPING_TARGET_CHOICE Node = 180
	PARSE_SEGMENT_TEMPLATE_CALL_SEGMENT Node = 181
	PARSE_TEMPLATE_BODY Node = 182
	PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_SEGMENT Node = 183
	PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_LEX Node = 184
	PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_NEST Node = 185
	PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_PARSE_SEGMENT Node = 186
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_SEGMENT Node = 187
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_LEX Node = 188
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_NEST Node = 189
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_PARSE_SEGMENT Node = 190
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_SEGMENT Node = 191
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_LEX Node = 192
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_NEST Node = 193
	PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_PARSE_SEGMENT Node = 194
	PARSE_TEMPLATE_CALL_ARGS_SEGMENT Node = 195
	PARSE_TEMPLATE_CALL_ARGS_USING_LEX Node = 196
	PARSE_TEMPLATE_CALL_ARGS_USING_NEST Node = 197
	PARSE_TEMPLATE_CALL_ARGS_USING_PARSE_SEGMENT Node = 198
	PARSE_TEMPLATE_DECLARATION Node = 199
	PARSE_TEMPLATE_PARAMETER Node = 200
	PARSE_TEMPLATE_PARAMETER_LIST Node = 201
	PARSE_TEMPLATE_SIGNATURE Node = 202
	PATTERN_CLASS Node = 203
	PATTERN_CLASS_ITEM_COMMA Node = 204
	PATTERN_CLASS_ITEM_LIST Node = 205
	PATTERN_CLASS_ITEM_SEQ Node = 206
	PATTERN_DEFINITION Node = 207
	PATTERN_DEFINITION_LIST Node = 208
	PATTERN_EXPRESSION Node = 209
	PATTERN_EXPRESSION_BP_10 Node = 210
	PATTERN_EXPRESSION_BP_20 Node = 211
	PATTERN_EXPRESSION_BP_30 Node = 212
	PATTERN_EXPRESSION_BP_40 Node = 213
	PATTERN_EXPRESSION_BP_60 Node = 214
	PATTERN_GROUP Node = 215
	PATTERN_RANGE_TAIL Node = 216
	PATTERN_REF Node = 217
	PATTERN_SECTION Node = 218
	PATTERN_SECTION_BLOCK_NEST Node = 219
	PATTERN_SEGMENT Node = 220
	PRAGMA_BLOCK Node = 221
	PRAGMA_BLOCK_BLOCK_NEST Node = 222
	PRAGMA_BLOCK_KEY Node = 223
	PRAGMA_BLOCK_KEY_SEGMENT Node = 224
	PRAGMA_BLOCK_LIST Node = 225
	PRAGMA_CONFIGURATION Node = 226
	PRAGMA_CONFIGURATION_LIST Node = 227
	PRAGMA_SECTION Node = 228
	PRAGMA_SECTION_BLOCK_NEST Node = 229
	PRAGMA_VALUE Node = 230
	PRATT_CATEGORY Node = 231
	PRATT_CATEGORY_LIST Node = 232
	PRATT_EXPR_BODY Node = 233
	PRATT_EXPR_DEF Node = 234
	PRATT_EXPR_DEF_LIST Node = 235
	PRATT_IMPLICIT Node = 236
	PRATT_IMPLICIT_BODY Node = 237
	PRATT_IMPLICIT_DEF Node = 238
	PRATT_INFIX Node = 239
	PRATT_INFIX_BODY Node = 240
	PRATT_INFIX_LIST Node = 241
	PRATT_OPERATOR_DEF_INFIX Node = 242
	PRATT_OPERATOR_DEF_POSTFIX Node = 243
	PRATT_OPERATOR_DEF_PREFIX Node = 244
	PRATT_POSTFIX Node = 245
	PRATT_POSTFIX_BODY Node = 246
	PRATT_POSTFIX_LIST Node = 247
	PRATT_PREFIX Node = 248
	PRATT_PREFIX_BODY Node = 249
	PRATT_PREFIX_LIST Node = 250
	PRATT_PRIMARY Node = 251
	PRATT_PRIMARY_BODY Node = 252
	PRATT_PRIMARY_REF Node = 253
	PRATT_SECTION Node = 254
	PRATT_SECTION_BLOCK_NEST Node = 255
	PREDICT_LOOKAHEAD Node = 256
	PREDICT_LOOKAHEAD_ITEMS Node = 257
	PREDICT_LOOKAHEAD_LIST Node = 258
	PREFIX_DUMMY_RULE_PATTERNS Node = 259
	REPETITION_BOUNDS Node = 260
	REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ Node = 261
	REPETITION_BOUNDS_NEST Node = 262
	REPETITION_BOUNDS_STARTS_WITH_COMMA Node = 263
	REPETITION_BOUNDS_STARTS_WITH_MIN Node = 264
	RULE_MODIFIER_SYNC Node = 265
	STATE_DEFINITION_BODY Node = 266
	STATE_DEFINITION_LIST Node = 267
	STATE_DEFINITION_TAIL Node = 268
	STATE_DEFINITION_TAIL_CONTENT Node = 269
	STATE_LIST Node = 270
	STATE_LIST_BLOCKS Node = 271
	STATE_MUTATION_ARGUMENT_LIST_ARGS Node = 272
	STATE_MUTATION_ARGUMENT_LIST_LIST Node = 273
	STATE_MUTATION_ARGUMENT_LIST_POP Node = 274
	STATE_MUTATION_ARGUMENT_LIST_TAIL Node = 275
	STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT Node = 276
	STATE_MUTATION_POP Node = 277
	STATE_MUTATION_PUSH Node = 278
	STATE_MUTATION_SET Node = 279
	STRING_ARRAY Node = 280
	STRING_ARRAY_ELEMENT_LIST Node = 281
	STRING_ARRAY_ELEMENT_LIST_TAIL Node = 282
	STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT Node = 283
	SYNC_BLOCK Node = 284
	SYNC_TOKEN_LIST Node = 285
	TEMPLATE_ARGUMENT_LIST_TAIL Node = 286
	TEMPLATE_ARGUMENT_LIST_TAIL_CONTENT Node = 287
	gr_DUMMY_CHOICE_FOR_PRAGMA_VALUES Node = 288
	gr_DUMMY_CHOICE_IDENT_MAP_BASE Node = 289
	gr_DUMMY_CHOICE_NEST Node = 290
	gr_DUMMY_CHOICE_PARSE_BLOCK_CHOICE Node = 291
	gr_DUMMY_CHOICE_PARSE_BLOCK_LIST Node = 292
	gr_DUMMY_CHOICE_VIRTUAL_MAPPING Node = 293
	gr_HEADER Node = 294
	gr_IMPORT_DEFINITION_LIST Node = 295
	gr_IMPORT_SECTION_BLOCK_NEST Node = 296
	gr_LEX_RULE_LIST Node = 297
	gr_LEX_RULE_PATTERN Node = 298
	gr_LEX_RULE_STATE_MUTATION_KIND Node = 299
	gr_LEX_SECTION_BLOCK_NEST Node = 300
	gr_META_KEY_VALUE_PAIR Node = 301
	gr_NodePatternRef Node = 302
	gr_PARSE_EXPRESSION Node = 303
	gr_PARSE_EXPRESSION_BP_10 Node = 304
	gr_PARSE_EXPRESSION_BP_20 Node = 305
	gr_PARSE_EXPRESSION_BP_30 Node = 306
	gr_PARSE_EXPRESSION_BP_40 Node = 307
	gr_PARSE_IGNORE_ROLE_LIST Node = 308
	gr_PARSE_IGNORE_SECTION_BLOCK_NEST Node = 309
	gr_PARSE_OP_NEST_CHOICE Node = 310
	gr_PARSE_OP_NEST_EXPLICIT Node = 311
	gr_PARSE_SECTION_BLOCK_NEST Node = 312
	gr_PARSE_SEGMENT Node = 313
	gr_PARSE_SEGMENT_MAPPING_TARGET_CHOICE Node = 314
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_SEGMENT Node = 315
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_LEX Node = 316
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_NEST Node = 317
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_PARSE_SEGMENT Node = 318
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_SEGMENT Node = 319
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_LEX Node = 320
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_NEST Node = 321
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_PARSE_SEGMENT Node = 322
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_SEGMENT Node = 323
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_LEX Node = 324
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_NEST Node = 325
	gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_PARSE_SEGMENT Node = 326
	gr_PARSE_TEMPLATE_SIGNATURE Node = 327
	gr_PATTERN_CLASS_ITEM_LIST Node = 328
	gr_PATTERN_DEFINITION_LIST Node = 329
	gr_PATTERN_EXPRESSION Node = 330
	gr_PATTERN_EXPRESSION_BP_10 Node = 331
	gr_PATTERN_EXPRESSION_BP_20 Node = 332
	gr_PATTERN_EXPRESSION_BP_30 Node = 333
	gr_PATTERN_EXPRESSION_BP_40 Node = 334
	gr_PATTERN_EXPRESSION_BP_60 Node = 335
	gr_PATTERN_SECTION_BLOCK_NEST Node = 336
	gr_PATTERN_SEGMENT Node = 337
	gr_PRAGMA_BLOCK_BLOCK_NEST Node = 338
	gr_PRAGMA_BLOCK_LIST Node = 339
	gr_PRAGMA_CONFIGURATION_LIST Node = 340
	gr_PRAGMA_SECTION_BLOCK_NEST Node = 341
	gr_PRATT_CATEGORY Node = 342
	gr_PRATT_CATEGORY_LIST Node = 343
	gr_PRATT_EXPR_DEF_LIST Node = 344
	gr_PRATT_INFIX_LIST Node = 345
	gr_PRATT_POSTFIX_LIST Node = 346
	gr_PRATT_PREFIX_LIST Node = 347
	gr_PRATT_SECTION_BLOCK_NEST Node = 348
	gr_PREDICT_LOOKAHEAD_ITEMS Node = 349
	gr_PREFIX_DUMMY_RULE_PATTERNS Node = 350
	gr_REPETITION_BOUNDS Node = 351
	gr_REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ Node = 352
	gr_REPETITION_BOUNDS_NEST Node = 353
	gr_STATE_DEFINITION_TAIL Node = 354
	gr_STATE_DEFINITION_TAIL_CONTENT Node = 355
	gr_STATE_LIST_BLOCKS Node = 356
	gr_STATE_MUTATION_ARGUMENT_LIST_TAIL Node = 357
	gr_STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT Node = 358
	gr_STRING_ARRAY_ELEMENT_LIST Node = 359
	gr_STRING_ARRAY_ELEMENT_LIST_TAIL Node = 360
	gr_STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT Node = 361
	gr_SYNC_TOKEN_LIST Node = 362
	gr_TEMPLATE_ARGUMENT_LIST_TAIL Node = 363
	gr_TEMPLATE_ARGUMENT_LIST_TAIL_CONTENT Node = 364
)

var NodeNames = [...]string{
	"DUMMY_CHOICE_FOR_PRAGMA_VALUES",
	"DUMMY_CHOICE_IDENT_MAP_BASE",
	"DUMMY_CHOICE_NEST",
	"DUMMY_CHOICE_PARSE_BLOCK_CHOICE",
	"DUMMY_CHOICE_PARSE_BLOCK_LIST",
	"DUMMY_CHOICE_VIRTUAL_MAPPING",
	"ERROR_NODE",
	"HEADER",
	"HEADER_CONTENT",
	"IMPORT_DEFINITION",
	"IMPORT_DEFINITION_LIST",
	"IMPORT_SECTION",
	"IMPORT_SECTION_BLOCK_NEST",
	"LEX_RULE",
	"LEX_RULE_LIST",
	"LEX_RULE_PATTERN",
	"LEX_RULE_PATTERN_USING_LEX",
	"LEX_RULE_PATTERN_USING_NEST",
	"LEX_RULE_PATTERN_USING_PARSE_SEGMENT",
	"LEX_RULE_STATE_MUTATION",
	"LEX_RULE_STATE_MUTATION_KIND",
	"LEX_SECTION",
	"LEX_SECTION_BLOCK_NEST",
	"META_KEY_VALUE_PAIR",
	"META_KEY_VALUE_SEQUENCE",
	"META_SECTION",
	"NodeCharLiteral",
	"NodeDSLName",
	"NodeExported",
	"NodeHeader",
	"NodeImportAlias",
	"NodeImportDefinition",
	"NodeImportKeyword",
	"NodeImportPath",
	"NodeImportSection",
	"NodeLSPECName",
	"NodeLexKeyword",
	"NodeLexRule",
	"NodeLexRulePattern",
	"NodeLexRulePatternUsing",
	"NodeLexRulePriority",
	"NodeLexRuleRole",
	"NodeLexRuleStateMutation",
	"NodeLexRuleTokenName",
	"NodeLexSection",
	"NodeLocalVariable",
	"NodeMetaKey",
	"NodeMetaKeyValuePair",
	"NodeMetaSection",
	"NodeMetaValue",
	"NodeModuleReference",
	"NodeParseBlock",
	"NodeParseExpressionReference",
	"NodeParseGroup",
	"NodeParseIgnoreKeyword",
	"NodeParseIgnoreRole",
	"NodeParseIgnoreSection",
	"NodeParseKeyword",
	"NodeParseModifierPredict",
	"NodeParseNestBody",
	"NodeParseNestCloseToken",
	"NodeParseNestOpenToken",
	"NodeParseNestPairRef",
	"NodeParseNodeName",
	"NodeParseOpNest",
	"NodeParseOpSuppress",
	"NodeParsePair",
	"NodeParsePairIdentifier",
	"NodeParseRule",
	"NodeParseRuleBody",
	"NodeParseRuleName",
	"NodeParseSection",
	"NodeParseSectionBody",
	"NodeParseSegment",
	"NodeParseSymbolReference",
	"NodeParseTemplate",
	"NodeParseTemplateBody",
	"NodeParseTemplateCallArgs",
	"NodeParseTemplateCallArgument",
	"NodeParseTemplateCallKeyword",
	"NodeParseTemplateIdentifier",
	"NodeParseTemplateParameter",
	"NodeParseTemplateParameterIdentifier",
	"NodeParseTemplateParameterList",
	"NodeParseTemplateParameterReference",
	"NodeParseTemplateParameterType",
	"NodeParseTemplateReference",
	"NodeParseTokenReference",
	"NodePatternAny",
	"NodePatternClass",
	"NodePatternClassItem",
	"NodePatternDefName",
	"NodePatternDefinition",
	"NodePatternExternalPatternReference",
	"NodePatternGroup",
	"NodePatternKeyword",
	"NodePatternRange",
	"NodePatternRef",
	"NodePatternRegEx",
	"NodePatternSection",
	"NodePragmaBlock",
	"NodePragmaBlockKey",
	"NodePragmaBlockKeyPrefix",
	"NodePragmaBlockKeySegment",
	"NodePragmaConfiguration",
	"NodePragmaKey",
	"NodePragmaKeyword",
	"NodePragmaSection",
	"NodePragmaValue",
	"NodePrattExprBody",
	"NodePrattExprDef",
	"NodePrattExprName",
	"NodePrattImplicit",
	"NodePrattImplicitBody",
	"NodePrattImplicitDef",
	"NodePrattInfix",
	"NodePrattInfixBody",
	"NodePrattKeyword",
	"NodePrattLeftPrecedenceValue",
	"NodePrattOperatorDef",
	"NodePrattPostfix",
	"NodePrattPostfixBody",
	"NodePrattPrefix",
	"NodePrattPrefixBody",
	"NodePrattPrimary",
	"NodePrattPrimaryBody",
	"NodePrattPrimaryRef",
	"NodePrattRightPrecedenceValue",
	"NodePrattSection",
	"NodePredictLookahead",
	"NodePredictLookaheadList",
	"NodePredictOffset",
	"NodePredictToken",
	"NodeProgram",
	"NodeRepetitionBounds",
	"NodeRepetitionMax",
	"NodeRepetitionMin",
	"NodeRuleModifierSync",
	"NodeRuleModifierTransparent",
	"NodeStateDefinition",
	"NodeStateDefinitionBody",
	"NodeStateDefinitionList",
	"NodeStateKeyword",
	"NodeStateList",
	"NodeStateMutationArgumentList",
	"NodeStateMutationPop",
	"NodeStateMutationPopAmount",
	"NodeStateMutationPush",
	"NodeStateMutationSet",
	"NodeStateReference",
	"NodeStringArray",
	"NodeStringLiteral",
	"NodeSyncBlock",
	"NodeSyncToken",
	"NodeVersion",
	"PARSE_BLOCK",
	"PARSE_EXPRESSION_BP_10",
	"PARSE_EXPRESSION_BP_20",
	"PARSE_EXPRESSION_BP_30",
	"PARSE_EXPRESSION_BP_40",
	"PARSE_GROUP",
	"PARSE_IGNORE_ROLE_LIST",
	"PARSE_IGNORE_SECTION",
	"PARSE_IGNORE_SECTION_BLOCK_NEST",
	"PARSE_MODIFIER_PREDICT",
	"PARSE_NEST_BODY",
	"PARSE_OP_NEST",
	"PARSE_OP_NEST_CHOICE",
	"PARSE_OP_NEST_EXPLICIT",
	"PARSE_OP_SUPPRESS",
	"PARSE_PAIR_DECLARATION",
	"PARSE_RULE",
	"PARSE_RULE_BODY",
	"PARSE_SECTION",
	"PARSE_SECTION_BLOCK_NEST",
	"PARSE_SECTION_BODY",
	"PARSE_SEGMENT",
	"PARSE_SEGMENT_IDENT_MAPPING_OR_CALL",
	"PARSE_SEGMENT_MAPPING_TAIL",
	"PARSE_SEGMENT_MAPPING_TARGET_CHOICE",
	"PARSE_SEGMENT_TEMPLATE_CALL_SEGMENT",
	"PARSE_TEMPLATE_BODY",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_LEX",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_NEST",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_PARSE_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_LEX",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_NEST",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_PARSE_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_LEX",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_NEST",
	"PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_PARSE_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_SEGMENT",
	"PARSE_TEMPLATE_CALL_ARGS_USING_LEX",
	"PARSE_TEMPLATE_CALL_ARGS_USING_NEST",
	"PARSE_TEMPLATE_CALL_ARGS_USING_PARSE_SEGMENT",
	"PARSE_TEMPLATE_DECLARATION",
	"PARSE_TEMPLATE_PARAMETER",
	"PARSE_TEMPLATE_PARAMETER_LIST",
	"PARSE_TEMPLATE_SIGNATURE",
	"PATTERN_CLASS",
	"PATTERN_CLASS_ITEM_COMMA",
	"PATTERN_CLASS_ITEM_LIST",
	"PATTERN_CLASS_ITEM_SEQ",
	"PATTERN_DEFINITION",
	"PATTERN_DEFINITION_LIST",
	"PATTERN_EXPRESSION",
	"PATTERN_EXPRESSION_BP_10",
	"PATTERN_EXPRESSION_BP_20",
	"PATTERN_EXPRESSION_BP_30",
	"PATTERN_EXPRESSION_BP_40",
	"PATTERN_EXPRESSION_BP_60",
	"PATTERN_GROUP",
	"PATTERN_RANGE_TAIL",
	"PATTERN_REF",
	"PATTERN_SECTION",
	"PATTERN_SECTION_BLOCK_NEST",
	"PATTERN_SEGMENT",
	"PRAGMA_BLOCK",
	"PRAGMA_BLOCK_BLOCK_NEST",
	"PRAGMA_BLOCK_KEY",
	"PRAGMA_BLOCK_KEY_SEGMENT",
	"PRAGMA_BLOCK_LIST",
	"PRAGMA_CONFIGURATION",
	"PRAGMA_CONFIGURATION_LIST",
	"PRAGMA_SECTION",
	"PRAGMA_SECTION_BLOCK_NEST",
	"PRAGMA_VALUE",
	"PRATT_CATEGORY",
	"PRATT_CATEGORY_LIST",
	"PRATT_EXPR_BODY",
	"PRATT_EXPR_DEF",
	"PRATT_EXPR_DEF_LIST",
	"PRATT_IMPLICIT",
	"PRATT_IMPLICIT_BODY",
	"PRATT_IMPLICIT_DEF",
	"PRATT_INFIX",
	"PRATT_INFIX_BODY",
	"PRATT_INFIX_LIST",
	"PRATT_OPERATOR_DEF_INFIX",
	"PRATT_OPERATOR_DEF_POSTFIX",
	"PRATT_OPERATOR_DEF_PREFIX",
	"PRATT_POSTFIX",
	"PRATT_POSTFIX_BODY",
	"PRATT_POSTFIX_LIST",
	"PRATT_PREFIX",
	"PRATT_PREFIX_BODY",
	"PRATT_PREFIX_LIST",
	"PRATT_PRIMARY",
	"PRATT_PRIMARY_BODY",
	"PRATT_PRIMARY_REF",
	"PRATT_SECTION",
	"PRATT_SECTION_BLOCK_NEST",
	"PREDICT_LOOKAHEAD",
	"PREDICT_LOOKAHEAD_ITEMS",
	"PREDICT_LOOKAHEAD_LIST",
	"PREFIX_DUMMY_RULE_PATTERNS",
	"REPETITION_BOUNDS",
	"REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ",
	"REPETITION_BOUNDS_NEST",
	"REPETITION_BOUNDS_STARTS_WITH_COMMA",
	"REPETITION_BOUNDS_STARTS_WITH_MIN",
	"RULE_MODIFIER_SYNC",
	"STATE_DEFINITION_BODY",
	"STATE_DEFINITION_LIST",
	"STATE_DEFINITION_TAIL",
	"STATE_DEFINITION_TAIL_CONTENT",
	"STATE_LIST",
	"STATE_LIST_BLOCKS",
	"STATE_MUTATION_ARGUMENT_LIST_ARGS",
	"STATE_MUTATION_ARGUMENT_LIST_LIST",
	"STATE_MUTATION_ARGUMENT_LIST_POP",
	"STATE_MUTATION_ARGUMENT_LIST_TAIL",
	"STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT",
	"STATE_MUTATION_POP",
	"STATE_MUTATION_PUSH",
	"STATE_MUTATION_SET",
	"STRING_ARRAY",
	"STRING_ARRAY_ELEMENT_LIST",
	"STRING_ARRAY_ELEMENT_LIST_TAIL",
	"STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT",
	"SYNC_BLOCK",
	"SYNC_TOKEN_LIST",
	"TEMPLATE_ARGUMENT_LIST_TAIL",
	"TEMPLATE_ARGUMENT_LIST_TAIL_CONTENT",
	"gr_DUMMY_CHOICE_FOR_PRAGMA_VALUES",
	"gr_DUMMY_CHOICE_IDENT_MAP_BASE",
	"gr_DUMMY_CHOICE_NEST",
	"gr_DUMMY_CHOICE_PARSE_BLOCK_CHOICE",
	"gr_DUMMY_CHOICE_PARSE_BLOCK_LIST",
	"gr_DUMMY_CHOICE_VIRTUAL_MAPPING",
	"gr_HEADER",
	"gr_IMPORT_DEFINITION_LIST",
	"gr_IMPORT_SECTION_BLOCK_NEST",
	"gr_LEX_RULE_LIST",
	"gr_LEX_RULE_PATTERN",
	"gr_LEX_RULE_STATE_MUTATION_KIND",
	"gr_LEX_SECTION_BLOCK_NEST",
	"gr_META_KEY_VALUE_PAIR",
	"gr_NodePatternRef",
	"gr_PARSE_EXPRESSION",
	"gr_PARSE_EXPRESSION_BP_10",
	"gr_PARSE_EXPRESSION_BP_20",
	"gr_PARSE_EXPRESSION_BP_30",
	"gr_PARSE_EXPRESSION_BP_40",
	"gr_PARSE_IGNORE_ROLE_LIST",
	"gr_PARSE_IGNORE_SECTION_BLOCK_NEST",
	"gr_PARSE_OP_NEST_CHOICE",
	"gr_PARSE_OP_NEST_EXPLICIT",
	"gr_PARSE_SECTION_BLOCK_NEST",
	"gr_PARSE_SEGMENT",
	"gr_PARSE_SEGMENT_MAPPING_TARGET_CHOICE",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_SEGMENT",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_LEX",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_NEST",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_DUMMY_USING_PARSE_SEGMENT",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_SEGMENT",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_LEX",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_NEST",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_CONTENT_USING_PARSE_SEGMENT",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_SEGMENT",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_LEX",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_NEST",
	"gr_PARSE_TEMPLATE_CALL_ARGS_LIST_TAIL_USING_PARSE_SEGMENT",
	"gr_PARSE_TEMPLATE_SIGNATURE",
	"gr_PATTERN_CLASS_ITEM_LIST",
	"gr_PATTERN_DEFINITION_LIST",
	"gr_PATTERN_EXPRESSION",
	"gr_PATTERN_EXPRESSION_BP_10",
	"gr_PATTERN_EXPRESSION_BP_20",
	"gr_PATTERN_EXPRESSION_BP_30",
	"gr_PATTERN_EXPRESSION_BP_40",
	"gr_PATTERN_EXPRESSION_BP_60",
	"gr_PATTERN_SECTION_BLOCK_NEST",
	"gr_PATTERN_SEGMENT",
	"gr_PRAGMA_BLOCK_BLOCK_NEST",
	"gr_PRAGMA_BLOCK_LIST",
	"gr_PRAGMA_CONFIGURATION_LIST",
	"gr_PRAGMA_SECTION_BLOCK_NEST",
	"gr_PRATT_CATEGORY",
	"gr_PRATT_CATEGORY_LIST",
	"gr_PRATT_EXPR_DEF_LIST",
	"gr_PRATT_INFIX_LIST",
	"gr_PRATT_POSTFIX_LIST",
	"gr_PRATT_PREFIX_LIST",
	"gr_PRATT_SECTION_BLOCK_NEST",
	"gr_PREDICT_LOOKAHEAD_ITEMS",
	"gr_PREFIX_DUMMY_RULE_PATTERNS",
	"gr_REPETITION_BOUNDS",
	"gr_REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ",
	"gr_REPETITION_BOUNDS_NEST",
	"gr_STATE_DEFINITION_TAIL",
	"gr_STATE_DEFINITION_TAIL_CONTENT",
	"gr_STATE_LIST_BLOCKS",
	"gr_STATE_MUTATION_ARGUMENT_LIST_TAIL",
	"gr_STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT",
	"gr_STRING_ARRAY_ELEMENT_LIST",
	"gr_STRING_ARRAY_ELEMENT_LIST_TAIL",
	"gr_STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT",
	"gr_SYNC_TOKEN_LIST",
	"gr_TEMPLATE_ARGUMENT_LIST_TAIL",
	"gr_TEMPLATE_ARGUMENT_LIST_TAIL_CONTENT",
}

func (t Node) String() string {
	if t < 1 || int(t-1) >= len(NodeNames) {
		return "Node(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return NodeNames[t-1]
}
