// Code generated by LangSpec. DO NOT EDIT.

package compiler

import (
	"lexarch"
	"strconv"
)

// Token represents a Token generated by LangSpec (IDs match compiler symbol table).
type Token = lexarch.TokenKind

const (
	TokAssignment Token = 2
	TokBlockComment Token = 3
	TokBraceClose Token = 4
	TokBraceOpen Token = 5
	TokBracketClose Token = 6
	TokBracketOpen Token = 7
	TokChainSeparator Token = 8
	TokCharLiteral Token = 9
	TokComma Token = 10
	TokDashes Token = 11
	TokDot Token = 12
	TokEOF Token = 13
	TokEqualsOperator Token = 14
	TokIdentifier Token = 15
	TokInteger Token = 16
	TokKWFalse Token = 17
	TokKWIgnore Token = 18
	TokKWImplicit Token = 19
	TokKWInfix Token = 20
	TokKWLSpec Token = 21
	TokKWLex Token = 22
	TokKWLocal Token = 23
	TokKWNest Token = 24
	TokKWParse Token = 25
	TokKWPattern Token = 26
	TokKWPop Token = 27
	TokKWPostfix Token = 28
	TokKWPragma Token = 29
	TokKWPratt Token = 30
	TokKWPrecedence Token = 31
	TokKWPredict Token = 32
	TokKWPrefix Token = 33
	TokKWPrimary Token = 34
	TokKWPush Token = 35
	TokKWSet Token = 36
	TokKWState Token = 37
	TokKWSync Token = 38
	TokKWTool Token = 39
	TokKWTransparent Token = 40
	TokKWTrue Token = 41
	TokKWVirtual Token = 42
	TokLineComment Token = 43
	TokMetaSection Token = 44
	TokNegation Token = 45
	TokOptional Token = 46
	TokParenClose Token = 47
	TokParenOpen Token = 48
	TokPipe Token = 49
	TokPlus Token = 50
	TokRange Token = 51
	TokRegexLiteral Token = 52
	TokSemicolon Token = 53
	TokStar Token = 54
	TokStringLiteral Token = 55
	TokVersion Token = 56
	TokWhitespace Token = 57
)

var TokenNames = [...]string{
	"TokAssignment",
	"TokBlockComment",
	"TokBraceClose",
	"TokBraceOpen",
	"TokBracketClose",
	"TokBracketOpen",
	"TokChainSeparator",
	"TokCharLiteral",
	"TokComma",
	"TokDashes",
	"TokDot",
	"TokEOF",
	"TokEqualsOperator",
	"TokIdentifier",
	"TokInteger",
	"TokKWFalse",
	"TokKWIgnore",
	"TokKWImplicit",
	"TokKWInfix",
	"TokKWLSpec",
	"TokKWLex",
	"TokKWLocal",
	"TokKWNest",
	"TokKWParse",
	"TokKWPattern",
	"TokKWPop",
	"TokKWPostfix",
	"TokKWPragma",
	"TokKWPratt",
	"TokKWPrecedence",
	"TokKWPredict",
	"TokKWPrefix",
	"TokKWPrimary",
	"TokKWPush",
	"TokKWSet",
	"TokKWState",
	"TokKWSync",
	"TokKWTool",
	"TokKWTransparent",
	"TokKWTrue",
	"TokKWVirtual",
	"TokLineComment",
	"TokMetaSection",
	"TokNegation",
	"TokOptional",
	"TokParenClose",
	"TokParenOpen",
	"TokPipe",
	"TokPlus",
	"TokRange",
	"TokRegexLiteral",
	"TokSemicolon",
	"TokStar",
	"TokStringLiteral",
	"TokVersion",
	"TokWhitespace",
}

func TokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "Token(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return TokenNames[t-2]
}

func TokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "", false
	}
	return TokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(TokenTokenKindStringResolver)
}

// Node represents a Node generated by LangSpec (IDs match compiler symbol table).
type Node uint32

const (
	DUMMY_CHOICE_FOR_PATTERNS Node = 1
	DUMMY_CHOICE_FOR_PRAGMA_VALUES Node = 2
	DUMMY_CHOICE_NEST Node = 3
	DUMMY_LOCAL_VAR_FOR_PATTERNS Node = 4
	ERROR_NODE Node = 5
	HEADER Node = 6
	HEADER_CONTENT Node = 7
	LEX_RULE Node = 8
	LEX_RULE_LIST Node = 9
	LEX_RULE_PATTERN Node = 10
	LEX_RULE_STATE_MUTATION Node = 11
	LEX_RULE_STATE_MUTATION_KIND Node = 12
	LEX_SECTION Node = 13
	LEX_SECTION_BLOCK_NEST Node = 14
	META_KEY_VALUE_PAIR Node = 15
	META_KEY_VALUE_SEQUENCE Node = 16
	META_SECTION Node = 17
	NodeCharLiteral Node = 18
	NodeDSLName Node = 19
	NodeHeader Node = 20
	NodeLSPECName Node = 21
	NodeLexKeyword Node = 22
	NodeLexRule Node = 23
	NodeLexRulePattern Node = 24
	NodeLexRulePriority Node = 25
	NodeLexRuleRole Node = 26
	NodeLexRuleStateMutation Node = 27
	NodeLexRuleTokenName Node = 28
	NodeLexSection Node = 29
	NodeLocalVariable Node = 30
	NodeMetaKey Node = 31
	NodeMetaKeyValuePair Node = 32
	NodeMetaSection Node = 33
	NodeMetaValue Node = 34
	NodeParseExpressionReference Node = 35
	NodeParseGroup Node = 36
	NodeParseIgnoreKeyword Node = 37
	NodeParseIgnoreRole Node = 38
	NodeParseIgnoreSection Node = 39
	NodeParseKeyword Node = 40
	NodeParseModifierPredict Node = 41
	NodeParseNestBody Node = 42
	NodeParseNestCloseToken Node = 43
	NodeParseNestOpenToken Node = 44
	NodeParseNodeName Node = 45
	NodeParseOpNest Node = 46
	NodeParseOpSuppress Node = 47
	NodeParseRule Node = 48
	NodeParseRuleBody Node = 49
	NodeParseRuleName Node = 50
	NodeParseSection Node = 51
	NodeParseSectionBody Node = 52
	NodeParseSegment Node = 53
	NodeParseSymbolReference Node = 54
	NodeParseTokenReference Node = 55
	NodePatternAny Node = 56
	NodePatternClass Node = 57
	NodePatternClassItem Node = 58
	NodePatternDefName Node = 59
	NodePatternDefinition Node = 60
	NodePatternGroup Node = 61
	NodePatternKeyword Node = 62
	NodePatternRange Node = 63
	NodePatternRef Node = 64
	NodePatternRegEx Node = 65
	NodePatternSection Node = 66
	NodePragmaBlock Node = 67
	NodePragmaBlockKey Node = 68
	NodePragmaBlockKeyPrefix Node = 69
	NodePragmaBlockKeySegment Node = 70
	NodePragmaConfiguration Node = 71
	NodePragmaKey Node = 72
	NodePragmaKeyword Node = 73
	NodePragmaSection Node = 74
	NodePragmaValue Node = 75
	NodePrattExprBody Node = 76
	NodePrattExprDef Node = 77
	NodePrattExprName Node = 78
	NodePrattImplicit Node = 79
	NodePrattImplicitBody Node = 80
	NodePrattImplicitDef Node = 81
	NodePrattInfix Node = 82
	NodePrattInfixBody Node = 83
	NodePrattKeyword Node = 84
	NodePrattLeftPrecedenceValue Node = 85
	NodePrattOperatorDef Node = 86
	NodePrattPostfix Node = 87
	NodePrattPostfixBody Node = 88
	NodePrattPrefix Node = 89
	NodePrattPrefixBody Node = 90
	NodePrattPrimary Node = 91
	NodePrattPrimaryBody Node = 92
	NodePrattPrimaryRef Node = 93
	NodePrattRightPrecedenceValue Node = 94
	NodePrattSection Node = 95
	NodePredictLookahead Node = 96
	NodePredictLookaheadList Node = 97
	NodePredictOffset Node = 98
	NodePredictToken Node = 99
	NodeProgram Node = 100
	NodeRepetitionBounds Node = 101
	NodeRepetitionMax Node = 102
	NodeRepetitionMin Node = 103
	NodeRuleModifierSync Node = 104
	NodeRuleModifierTransparent Node = 105
	NodeStateDefinition Node = 106
	NodeStateDefinitionBody Node = 107
	NodeStateDefinitionList Node = 108
	NodeStateKeyword Node = 109
	NodeStateList Node = 110
	NodeStateMutationArgumentList Node = 111
	NodeStateMutationPop Node = 112
	NodeStateMutationPopAmount Node = 113
	NodeStateMutationPush Node = 114
	NodeStateMutationSet Node = 115
	NodeStateReference Node = 116
	NodeStringArray Node = 117
	NodeStringLiteral Node = 118
	NodeSyncBlock Node = 119
	NodeSyncToken Node = 120
	NodeVersion Node = 121
	PARSE_EXPRESSION_BP_10 Node = 122
	PARSE_EXPRESSION_BP_20 Node = 123
	PARSE_EXPRESSION_BP_30 Node = 124
	PARSE_EXPRESSION_BP_40 Node = 125
	PARSE_GROUP Node = 126
	PARSE_IGNORE_ROLE_LIST Node = 127
	PARSE_IGNORE_SECTION Node = 128
	PARSE_IGNORE_SECTION_BLOCK_NEST Node = 129
	PARSE_MODIFIER_PREDICT Node = 130
	PARSE_NEST_BODY Node = 131
	PARSE_OP_NEST Node = 132
	PARSE_OP_SUPPRESS Node = 133
	PARSE_RULE Node = 134
	PARSE_RULE_BODY Node = 135
	PARSE_RULE_LIST Node = 136
	PARSE_SECTION Node = 137
	PARSE_SECTION_BLOCK_NEST Node = 138
	PARSE_SECTION_BODY Node = 139
	PARSE_SEGMENT Node = 140
	PARSE_SEGMENT_IDENT_MAPPING_OR_REF Node = 141
	PARSE_SEGMENT_TAIL Node = 142
	PARSE_SEGMENT_TAIL_CHOICE Node = 143
	PATTERN_CLASS Node = 144
	PATTERN_CLASS_ITEM_COMMA Node = 145
	PATTERN_CLASS_ITEM_LIST Node = 146
	PATTERN_CLASS_ITEM_SEQ Node = 147
	PATTERN_DEFINITION Node = 148
	PATTERN_DEFINITION_LIST Node = 149
	PATTERN_EXPRESSION Node = 150
	PATTERN_EXPRESSION_BP_10 Node = 151
	PATTERN_EXPRESSION_BP_20 Node = 152
	PATTERN_EXPRESSION_BP_30 Node = 153
	PATTERN_EXPRESSION_BP_40 Node = 154
	PATTERN_EXPRESSION_BP_60 Node = 155
	PATTERN_GROUP Node = 156
	PATTERN_RANGE_TAIL Node = 157
	PATTERN_REF Node = 158
	PATTERN_SECTION Node = 159
	PATTERN_SECTION_BLOCK_NEST Node = 160
	PATTERN_SEGMENT Node = 161
	PRAGMA_BLOCK Node = 162
	PRAGMA_BLOCK_BLOCK_NEST Node = 163
	PRAGMA_BLOCK_KEY Node = 164
	PRAGMA_BLOCK_KEY_sep Node = 165
	PRAGMA_BLOCK_KEY_tail Node = 166
	PRAGMA_BLOCK_LIST Node = 167
	PRAGMA_CONFIGURATION Node = 168
	PRAGMA_CONFIGURATION_LIST Node = 169
	PRAGMA_SECTION Node = 170
	PRAGMA_SECTION_BLOCK_NEST Node = 171
	PRAGMA_VALUE Node = 172
	PRATT_CATEGORY Node = 173
	PRATT_CATEGORY_LIST Node = 174
	PRATT_EXPR_BODY Node = 175
	PRATT_EXPR_DEF Node = 176
	PRATT_EXPR_DEF_LIST Node = 177
	PRATT_IMPLICIT Node = 178
	PRATT_IMPLICIT_BODY Node = 179
	PRATT_IMPLICIT_DEF Node = 180
	PRATT_INFIX Node = 181
	PRATT_INFIX_BODY Node = 182
	PRATT_INFIX_LIST Node = 183
	PRATT_OPERATOR_DEF_INFIX Node = 184
	PRATT_OPERATOR_DEF_POSTFIX Node = 185
	PRATT_OPERATOR_DEF_PREFIX Node = 186
	PRATT_POSTFIX Node = 187
	PRATT_POSTFIX_BODY Node = 188
	PRATT_POSTFIX_LIST Node = 189
	PRATT_PREFIX Node = 190
	PRATT_PREFIX_BODY Node = 191
	PRATT_PREFIX_LIST Node = 192
	PRATT_PRIMARY Node = 193
	PRATT_PRIMARY_BODY Node = 194
	PRATT_PRIMARY_REF Node = 195
	PRATT_SECTION Node = 196
	PRATT_SECTION_BLOCK_NEST Node = 197
	PREDICT_LOOKAHEAD Node = 198
	PREDICT_LOOKAHEAD_ITEMS Node = 199
	PREDICT_LOOKAHEAD_LIST Node = 200
	REPETITION_BOUNDS Node = 201
	REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ Node = 202
	REPETITION_BOUNDS_NEST Node = 203
	REPETITION_BOUNDS_STARTS_WITH_COMMA Node = 204
	REPETITION_BOUNDS_STARTS_WITH_MIN Node = 205
	RULE_MODIFIER_SYNC Node = 206
	STATE_DEFINITION_BODY Node = 207
	STATE_DEFINITION_LIST Node = 208
	STATE_DEFINITION_TAIL Node = 209
	STATE_DEFINITION_TAIL_CONTENT Node = 210
	STATE_LIST Node = 211
	STATE_LIST_BLOCKS Node = 212
	STATE_MUTATION_ARGUMENT_LIST_ARGS Node = 213
	STATE_MUTATION_ARGUMENT_LIST_LIST Node = 214
	STATE_MUTATION_ARGUMENT_LIST_POP Node = 215
	STATE_MUTATION_ARGUMENT_LIST_TAIL Node = 216
	STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT Node = 217
	STATE_MUTATION_POP Node = 218
	STATE_MUTATION_PUSH Node = 219
	STATE_MUTATION_SET Node = 220
	STRING_ARRAY Node = 221
	STRING_ARRAY_ELEMENT_LIST Node = 222
	STRING_ARRAY_ELEMENT_LIST_TAIL Node = 223
	STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT Node = 224
	SYNC_BLOCK Node = 225
	SYNC_TOKEN_LIST Node = 226
	gr_DUMMY_CHOICE_FOR_PATTERNS Node = 227
	gr_DUMMY_CHOICE_FOR_PRAGMA_VALUES Node = 228
	gr_DUMMY_CHOICE_NEST Node = 229
	gr_DUMMY_LOCAL_VAR_FOR_PATTERNS Node = 230
	gr_HEADER Node = 231
	gr_LEX_RULE_LIST Node = 232
	gr_LEX_RULE_PATTERN Node = 233
	gr_LEX_RULE_STATE_MUTATION_KIND Node = 234
	gr_LEX_SECTION_BLOCK_NEST Node = 235
	gr_META_KEY_VALUE_PAIR Node = 236
	gr_NodePatternRef Node = 237
	gr_PARSE_EXPRESSION Node = 238
	gr_PARSE_EXPRESSION_BP_10 Node = 239
	gr_PARSE_EXPRESSION_BP_20 Node = 240
	gr_PARSE_EXPRESSION_BP_30 Node = 241
	gr_PARSE_EXPRESSION_BP_40 Node = 242
	gr_PARSE_IGNORE_ROLE_LIST Node = 243
	gr_PARSE_IGNORE_SECTION_BLOCK_NEST Node = 244
	gr_PARSE_RULE_LIST Node = 245
	gr_PARSE_SECTION_BLOCK_NEST Node = 246
	gr_PARSE_SEGMENT Node = 247
	gr_PARSE_SEGMENT_TAIL_CHOICE Node = 248
	gr_PATTERN_CLASS_ITEM_LIST Node = 249
	gr_PATTERN_DEFINITION_LIST Node = 250
	gr_PATTERN_EXPRESSION Node = 251
	gr_PATTERN_EXPRESSION_BP_10 Node = 252
	gr_PATTERN_EXPRESSION_BP_20 Node = 253
	gr_PATTERN_EXPRESSION_BP_30 Node = 254
	gr_PATTERN_EXPRESSION_BP_40 Node = 255
	gr_PATTERN_EXPRESSION_BP_60 Node = 256
	gr_PATTERN_SECTION_BLOCK_NEST Node = 257
	gr_PATTERN_SEGMENT Node = 258
	gr_PRAGMA_BLOCK_BLOCK_NEST Node = 259
	gr_PRAGMA_BLOCK_KEY_sep Node = 260
	gr_PRAGMA_BLOCK_KEY_tail Node = 261
	gr_PRAGMA_BLOCK_LIST Node = 262
	gr_PRAGMA_CONFIGURATION_LIST Node = 263
	gr_PRAGMA_SECTION_BLOCK_NEST Node = 264
	gr_PRATT_CATEGORY Node = 265
	gr_PRATT_CATEGORY_LIST Node = 266
	gr_PRATT_EXPR_DEF_LIST Node = 267
	gr_PRATT_INFIX_LIST Node = 268
	gr_PRATT_POSTFIX_LIST Node = 269
	gr_PRATT_PREFIX_LIST Node = 270
	gr_PRATT_SECTION_BLOCK_NEST Node = 271
	gr_PREDICT_LOOKAHEAD_ITEMS Node = 272
	gr_REPETITION_BOUNDS Node = 273
	gr_REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ Node = 274
	gr_REPETITION_BOUNDS_NEST Node = 275
	gr_STATE_DEFINITION_TAIL Node = 276
	gr_STATE_DEFINITION_TAIL_CONTENT Node = 277
	gr_STATE_LIST_BLOCKS Node = 278
	gr_STATE_MUTATION_ARGUMENT_LIST_TAIL Node = 279
	gr_STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT Node = 280
	gr_STRING_ARRAY_ELEMENT_LIST Node = 281
	gr_STRING_ARRAY_ELEMENT_LIST_TAIL Node = 282
	gr_STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT Node = 283
	gr_SYNC_TOKEN_LIST Node = 284
)

var NodeNames = [...]string{
	"DUMMY_CHOICE_FOR_PATTERNS",
	"DUMMY_CHOICE_FOR_PRAGMA_VALUES",
	"DUMMY_CHOICE_NEST",
	"DUMMY_LOCAL_VAR_FOR_PATTERNS",
	"ERROR_NODE",
	"HEADER",
	"HEADER_CONTENT",
	"LEX_RULE",
	"LEX_RULE_LIST",
	"LEX_RULE_PATTERN",
	"LEX_RULE_STATE_MUTATION",
	"LEX_RULE_STATE_MUTATION_KIND",
	"LEX_SECTION",
	"LEX_SECTION_BLOCK_NEST",
	"META_KEY_VALUE_PAIR",
	"META_KEY_VALUE_SEQUENCE",
	"META_SECTION",
	"NodeCharLiteral",
	"NodeDSLName",
	"NodeHeader",
	"NodeLSPECName",
	"NodeLexKeyword",
	"NodeLexRule",
	"NodeLexRulePattern",
	"NodeLexRulePriority",
	"NodeLexRuleRole",
	"NodeLexRuleStateMutation",
	"NodeLexRuleTokenName",
	"NodeLexSection",
	"NodeLocalVariable",
	"NodeMetaKey",
	"NodeMetaKeyValuePair",
	"NodeMetaSection",
	"NodeMetaValue",
	"NodeParseExpressionReference",
	"NodeParseGroup",
	"NodeParseIgnoreKeyword",
	"NodeParseIgnoreRole",
	"NodeParseIgnoreSection",
	"NodeParseKeyword",
	"NodeParseModifierPredict",
	"NodeParseNestBody",
	"NodeParseNestCloseToken",
	"NodeParseNestOpenToken",
	"NodeParseNodeName",
	"NodeParseOpNest",
	"NodeParseOpSuppress",
	"NodeParseRule",
	"NodeParseRuleBody",
	"NodeParseRuleName",
	"NodeParseSection",
	"NodeParseSectionBody",
	"NodeParseSegment",
	"NodeParseSymbolReference",
	"NodeParseTokenReference",
	"NodePatternAny",
	"NodePatternClass",
	"NodePatternClassItem",
	"NodePatternDefName",
	"NodePatternDefinition",
	"NodePatternGroup",
	"NodePatternKeyword",
	"NodePatternRange",
	"NodePatternRef",
	"NodePatternRegEx",
	"NodePatternSection",
	"NodePragmaBlock",
	"NodePragmaBlockKey",
	"NodePragmaBlockKeyPrefix",
	"NodePragmaBlockKeySegment",
	"NodePragmaConfiguration",
	"NodePragmaKey",
	"NodePragmaKeyword",
	"NodePragmaSection",
	"NodePragmaValue",
	"NodePrattExprBody",
	"NodePrattExprDef",
	"NodePrattExprName",
	"NodePrattImplicit",
	"NodePrattImplicitBody",
	"NodePrattImplicitDef",
	"NodePrattInfix",
	"NodePrattInfixBody",
	"NodePrattKeyword",
	"NodePrattLeftPrecedenceValue",
	"NodePrattOperatorDef",
	"NodePrattPostfix",
	"NodePrattPostfixBody",
	"NodePrattPrefix",
	"NodePrattPrefixBody",
	"NodePrattPrimary",
	"NodePrattPrimaryBody",
	"NodePrattPrimaryRef",
	"NodePrattRightPrecedenceValue",
	"NodePrattSection",
	"NodePredictLookahead",
	"NodePredictLookaheadList",
	"NodePredictOffset",
	"NodePredictToken",
	"NodeProgram",
	"NodeRepetitionBounds",
	"NodeRepetitionMax",
	"NodeRepetitionMin",
	"NodeRuleModifierSync",
	"NodeRuleModifierTransparent",
	"NodeStateDefinition",
	"NodeStateDefinitionBody",
	"NodeStateDefinitionList",
	"NodeStateKeyword",
	"NodeStateList",
	"NodeStateMutationArgumentList",
	"NodeStateMutationPop",
	"NodeStateMutationPopAmount",
	"NodeStateMutationPush",
	"NodeStateMutationSet",
	"NodeStateReference",
	"NodeStringArray",
	"NodeStringLiteral",
	"NodeSyncBlock",
	"NodeSyncToken",
	"NodeVersion",
	"PARSE_EXPRESSION_BP_10",
	"PARSE_EXPRESSION_BP_20",
	"PARSE_EXPRESSION_BP_30",
	"PARSE_EXPRESSION_BP_40",
	"PARSE_GROUP",
	"PARSE_IGNORE_ROLE_LIST",
	"PARSE_IGNORE_SECTION",
	"PARSE_IGNORE_SECTION_BLOCK_NEST",
	"PARSE_MODIFIER_PREDICT",
	"PARSE_NEST_BODY",
	"PARSE_OP_NEST",
	"PARSE_OP_SUPPRESS",
	"PARSE_RULE",
	"PARSE_RULE_BODY",
	"PARSE_RULE_LIST",
	"PARSE_SECTION",
	"PARSE_SECTION_BLOCK_NEST",
	"PARSE_SECTION_BODY",
	"PARSE_SEGMENT",
	"PARSE_SEGMENT_IDENT_MAPPING_OR_REF",
	"PARSE_SEGMENT_TAIL",
	"PARSE_SEGMENT_TAIL_CHOICE",
	"PATTERN_CLASS",
	"PATTERN_CLASS_ITEM_COMMA",
	"PATTERN_CLASS_ITEM_LIST",
	"PATTERN_CLASS_ITEM_SEQ",
	"PATTERN_DEFINITION",
	"PATTERN_DEFINITION_LIST",
	"PATTERN_EXPRESSION",
	"PATTERN_EXPRESSION_BP_10",
	"PATTERN_EXPRESSION_BP_20",
	"PATTERN_EXPRESSION_BP_30",
	"PATTERN_EXPRESSION_BP_40",
	"PATTERN_EXPRESSION_BP_60",
	"PATTERN_GROUP",
	"PATTERN_RANGE_TAIL",
	"PATTERN_REF",
	"PATTERN_SECTION",
	"PATTERN_SECTION_BLOCK_NEST",
	"PATTERN_SEGMENT",
	"PRAGMA_BLOCK",
	"PRAGMA_BLOCK_BLOCK_NEST",
	"PRAGMA_BLOCK_KEY",
	"PRAGMA_BLOCK_KEY_sep",
	"PRAGMA_BLOCK_KEY_tail",
	"PRAGMA_BLOCK_LIST",
	"PRAGMA_CONFIGURATION",
	"PRAGMA_CONFIGURATION_LIST",
	"PRAGMA_SECTION",
	"PRAGMA_SECTION_BLOCK_NEST",
	"PRAGMA_VALUE",
	"PRATT_CATEGORY",
	"PRATT_CATEGORY_LIST",
	"PRATT_EXPR_BODY",
	"PRATT_EXPR_DEF",
	"PRATT_EXPR_DEF_LIST",
	"PRATT_IMPLICIT",
	"PRATT_IMPLICIT_BODY",
	"PRATT_IMPLICIT_DEF",
	"PRATT_INFIX",
	"PRATT_INFIX_BODY",
	"PRATT_INFIX_LIST",
	"PRATT_OPERATOR_DEF_INFIX",
	"PRATT_OPERATOR_DEF_POSTFIX",
	"PRATT_OPERATOR_DEF_PREFIX",
	"PRATT_POSTFIX",
	"PRATT_POSTFIX_BODY",
	"PRATT_POSTFIX_LIST",
	"PRATT_PREFIX",
	"PRATT_PREFIX_BODY",
	"PRATT_PREFIX_LIST",
	"PRATT_PRIMARY",
	"PRATT_PRIMARY_BODY",
	"PRATT_PRIMARY_REF",
	"PRATT_SECTION",
	"PRATT_SECTION_BLOCK_NEST",
	"PREDICT_LOOKAHEAD",
	"PREDICT_LOOKAHEAD_ITEMS",
	"PREDICT_LOOKAHEAD_LIST",
	"REPETITION_BOUNDS",
	"REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ",
	"REPETITION_BOUNDS_NEST",
	"REPETITION_BOUNDS_STARTS_WITH_COMMA",
	"REPETITION_BOUNDS_STARTS_WITH_MIN",
	"RULE_MODIFIER_SYNC",
	"STATE_DEFINITION_BODY",
	"STATE_DEFINITION_LIST",
	"STATE_DEFINITION_TAIL",
	"STATE_DEFINITION_TAIL_CONTENT",
	"STATE_LIST",
	"STATE_LIST_BLOCKS",
	"STATE_MUTATION_ARGUMENT_LIST_ARGS",
	"STATE_MUTATION_ARGUMENT_LIST_LIST",
	"STATE_MUTATION_ARGUMENT_LIST_POP",
	"STATE_MUTATION_ARGUMENT_LIST_TAIL",
	"STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT",
	"STATE_MUTATION_POP",
	"STATE_MUTATION_PUSH",
	"STATE_MUTATION_SET",
	"STRING_ARRAY",
	"STRING_ARRAY_ELEMENT_LIST",
	"STRING_ARRAY_ELEMENT_LIST_TAIL",
	"STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT",
	"SYNC_BLOCK",
	"SYNC_TOKEN_LIST",
	"gr_DUMMY_CHOICE_FOR_PATTERNS",
	"gr_DUMMY_CHOICE_FOR_PRAGMA_VALUES",
	"gr_DUMMY_CHOICE_NEST",
	"gr_DUMMY_LOCAL_VAR_FOR_PATTERNS",
	"gr_HEADER",
	"gr_LEX_RULE_LIST",
	"gr_LEX_RULE_PATTERN",
	"gr_LEX_RULE_STATE_MUTATION_KIND",
	"gr_LEX_SECTION_BLOCK_NEST",
	"gr_META_KEY_VALUE_PAIR",
	"gr_NodePatternRef",
	"gr_PARSE_EXPRESSION",
	"gr_PARSE_EXPRESSION_BP_10",
	"gr_PARSE_EXPRESSION_BP_20",
	"gr_PARSE_EXPRESSION_BP_30",
	"gr_PARSE_EXPRESSION_BP_40",
	"gr_PARSE_IGNORE_ROLE_LIST",
	"gr_PARSE_IGNORE_SECTION_BLOCK_NEST",
	"gr_PARSE_RULE_LIST",
	"gr_PARSE_SECTION_BLOCK_NEST",
	"gr_PARSE_SEGMENT",
	"gr_PARSE_SEGMENT_TAIL_CHOICE",
	"gr_PATTERN_CLASS_ITEM_LIST",
	"gr_PATTERN_DEFINITION_LIST",
	"gr_PATTERN_EXPRESSION",
	"gr_PATTERN_EXPRESSION_BP_10",
	"gr_PATTERN_EXPRESSION_BP_20",
	"gr_PATTERN_EXPRESSION_BP_30",
	"gr_PATTERN_EXPRESSION_BP_40",
	"gr_PATTERN_EXPRESSION_BP_60",
	"gr_PATTERN_SECTION_BLOCK_NEST",
	"gr_PATTERN_SEGMENT",
	"gr_PRAGMA_BLOCK_BLOCK_NEST",
	"gr_PRAGMA_BLOCK_KEY_sep",
	"gr_PRAGMA_BLOCK_KEY_tail",
	"gr_PRAGMA_BLOCK_LIST",
	"gr_PRAGMA_CONFIGURATION_LIST",
	"gr_PRAGMA_SECTION_BLOCK_NEST",
	"gr_PRATT_CATEGORY",
	"gr_PRATT_CATEGORY_LIST",
	"gr_PRATT_EXPR_DEF_LIST",
	"gr_PRATT_INFIX_LIST",
	"gr_PRATT_POSTFIX_LIST",
	"gr_PRATT_PREFIX_LIST",
	"gr_PRATT_SECTION_BLOCK_NEST",
	"gr_PREDICT_LOOKAHEAD_ITEMS",
	"gr_REPETITION_BOUNDS",
	"gr_REPETITION_BOUNDS_MIN_COMMA_MAX_OPT_SEQ",
	"gr_REPETITION_BOUNDS_NEST",
	"gr_STATE_DEFINITION_TAIL",
	"gr_STATE_DEFINITION_TAIL_CONTENT",
	"gr_STATE_LIST_BLOCKS",
	"gr_STATE_MUTATION_ARGUMENT_LIST_TAIL",
	"gr_STATE_MUTATION_ARGUMENT_LIST_TAIL_CONTENT",
	"gr_STRING_ARRAY_ELEMENT_LIST",
	"gr_STRING_ARRAY_ELEMENT_LIST_TAIL",
	"gr_STRING_ARRAY_ELEMENT_LIST_TAIL_CONTENT",
	"gr_SYNC_TOKEN_LIST",
}

func (t Node) String() string {
	if t < 1 || int(t-1) >= len(NodeNames) {
		return "Node(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return NodeNames[t-1]
}
