// Code generated by "stringer -type LangSpecLexerTokenRole"; DO NOT EDIT.

package spec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LANG_SPEC_STRUCTURAL_ROLE-1]
	_ = x[LANG_SPEC_WHITESPACE_ROLE-2]
	_ = x[LANG_SPEC_COMMENT_ROLE-3]
}

const _LangSpecLexerTokenRole_name = "LANG_SPEC_STRUCTURAL_ROLELANG_SPEC_WHITESPACE_ROLELANG_SPEC_COMMENT_ROLE"

var _LangSpecLexerTokenRole_index = [...]uint8{0, 25, 50, 72}

func (i LangSpecLexerTokenRole) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_LangSpecLexerTokenRole_index)-1 {
		return "LangSpecLexerTokenRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LangSpecLexerTokenRole_name[_LangSpecLexerTokenRole_index[idx]:_LangSpecLexerTokenRole_index[idx+1]]
}
