// Code generated by "stringer -type LangSpecLexerTokenType"; DO NOT EDIT.

package spec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokEOF-1]
	_ = x[TokWhitespace-2]
	_ = x[TokLineComment-3]
	_ = x[TokBlockComment-4]
	_ = x[TokDashes-5]
	_ = x[TokBraceOpen-6]
	_ = x[TokBraceClose-7]
	_ = x[TokParenOpen-8]
	_ = x[TokParenClose-9]
	_ = x[TokBracketOpen-10]
	_ = x[TokBracketClose-11]
	_ = x[TokSemicolon-12]
	_ = x[TokDot-13]
	_ = x[TokChainSeparator-14]
	_ = x[TokColon-15]
	_ = x[TokEqualsOperator-16]
	_ = x[TokMetaSection-17]
	_ = x[TokComma-18]
	_ = x[TokPipe-19]
	_ = x[TokRange-20]
	_ = x[TokStar-21]
	_ = x[TokSeparator-22]
	_ = x[TokNegation-23]
	_ = x[TokPlus-24]
	_ = x[TokOptional-25]
	_ = x[TokStringLiteral-26]
	_ = x[TokRegexLiteral-27]
	_ = x[TokCharLiteral-28]
	_ = x[TokVersion-29]
	_ = x[TokInteger-30]
	_ = x[TokIdentifier-31]
	_ = x[TokKWLSpec-32]
	_ = x[TokKWLex-33]
	_ = x[TokKWPattern-34]
	_ = x[TokKWPragma-35]
	_ = x[TokKWTool-36]
	_ = x[TokKWParse-37]
	_ = x[TokKWTrue-38]
	_ = x[TokKWFalse-39]
	_ = x[TokKWLocal-40]
	_ = x[TokKWVirtual-41]
	_ = x[TokKWNest-42]
	_ = x[TokKWPratt-43]
	_ = x[TokKWPrimary-44]
	_ = x[TokKWPrefix-45]
	_ = x[TokKWPostfix-46]
	_ = x[TokKWInfix-47]
	_ = x[TokKWImplicit-48]
	_ = x[TokKWPrecedence-49]
	_ = x[TokKWTransparent-50]
	_ = x[TokKWSync-51]
	_ = x[TokKWPredict-52]
	_ = x[TokKWIgnore-53]
	_ = x[TokKWState-54]
	_ = x[TokKWPush-55]
	_ = x[TokKWPop-56]
	_ = x[TokKWSet-57]
	_ = x[TokKWPair-58]
	_ = x[TokPairReference-59]
	_ = x[TokParameter-60]
	_ = x[TokKWRule-61]
	_ = x[TokKWTemplate-62]
	_ = x[TokKWCall-63]
	_ = x[TokKWImport-64]
	_ = x[TokKWExport-65]
	_ = x[TokKWAs-66]
	_ = x[TokKWUsing-67]
	_ = x[TokTypeToken-68]
	_ = x[TokTypeRule-69]
	_ = x[TokTypePrattExpr-70]
	_ = x[TokTypePair-71]
	_ = x[TokTypeNode-72]
}

const _LangSpecLexerTokenType_name = "TokEOFTokWhitespaceTokLineCommentTokBlockCommentTokDashesTokBraceOpenTokBraceCloseTokParenOpenTokParenCloseTokBracketOpenTokBracketCloseTokSemicolonTokDotTokChainSeparatorTokColonTokEqualsOperatorTokMetaSectionTokCommaTokPipeTokRangeTokStarTokSeparatorTokNegationTokPlusTokOptionalTokStringLiteralTokRegexLiteralTokCharLiteralTokVersionTokIntegerTokIdentifierTokKWLSpecTokKWLexTokKWPatternTokKWPragmaTokKWToolTokKWParseTokKWTrueTokKWFalseTokKWLocalTokKWVirtualTokKWNestTokKWPrattTokKWPrimaryTokKWPrefixTokKWPostfixTokKWInfixTokKWImplicitTokKWPrecedenceTokKWTransparentTokKWSyncTokKWPredictTokKWIgnoreTokKWStateTokKWPushTokKWPopTokKWSetTokKWPairTokPairReferenceTokParameterTokKWRuleTokKWTemplateTokKWCallTokKWImportTokKWExportTokKWAsTokKWUsingTokTypeTokenTokTypeRuleTokTypePrattExprTokTypePairTokTypeNode"

var _LangSpecLexerTokenType_index = [...]uint16{0, 6, 19, 33, 48, 57, 69, 82, 94, 107, 121, 136, 148, 154, 171, 179, 196, 210, 218, 225, 233, 240, 252, 263, 270, 281, 297, 312, 326, 336, 346, 359, 369, 377, 389, 400, 409, 419, 428, 438, 448, 460, 469, 479, 491, 502, 514, 524, 537, 552, 568, 577, 589, 600, 610, 619, 627, 635, 644, 660, 672, 681, 694, 703, 714, 725, 732, 742, 754, 765, 781, 792, 803}

func (i LangSpecLexerTokenType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_LangSpecLexerTokenType_index)-1 {
		return "LangSpecLexerTokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LangSpecLexerTokenType_name[_LangSpecLexerTokenType_index[idx]:_LangSpecLexerTokenType_index[idx+1]]
}
