// Code generated by "stringer -type LangSpecLexerState"; DO NOT EDIT.

package spec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LANG_SPEC_LEXER_STATE_DEFAULT-1]
}

const _LangSpecLexerState_name = "LANG_SPEC_LEXER_STATE_DEFAULT"

var _LangSpecLexerState_index = [...]uint8{0, 29}

func (i LangSpecLexerState) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_LangSpecLexerState_index)-1 {
		return "LangSpecLexerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LangSpecLexerState_name[_LangSpecLexerState_index[idx]:_LangSpecLexerState_index[idx+1]]
}
