package sublime

import (
	"fmt"
	"foundation/system"
	"langspec/editor"
	"sort"
	"strings"
	"time"

	"go.yaml.in/yaml/v4"
)

// -------------------------------------------------------- TYPES

/* SublimeTextGeneratorConfig encapsulates configuration for the generator. */
type SublimeTextGeneratorConfig[TToken comparable] struct {
	outputFile string

	languageName   string
	fileExtensions []string
	scope          string

	contextDefinitions []editor.Context[TToken]
	tokenStyles        []editor.TokenStyle[TToken]
	patternExtractor   editor.TokenPatternExtractor[TToken]
}

func SublimeTextGeneratorConfigCreate[TToken comparable](
	outputFile string,
	languageName, scope string,
	fileExtensions []string,
	gen *editor.GeneratedSyntax[TToken],
) *SublimeTextGeneratorConfig[TToken] {
	return &SublimeTextGeneratorConfig[TToken]{
		outputFile:         outputFile,
		languageName:       languageName,
		fileExtensions:     fileExtensions,
		scope:              scope,
		contextDefinitions: gen.ContextDefinitions,
		tokenStyles:        gen.TokenStyles,
		patternExtractor:   gen.PatternExtractor,
	}
}

// -------------------------------------------------------- GENERATOR

/*
SublimeTextGenerateSyntaxFile generates a Sublime Text .sublime-syntax file.
*/
func SublimeTextGenerateSyntaxFile[TToken comparable](
	config *SublimeTextGeneratorConfig[TToken],
) error {
	if config == nil {
		return fmt.Errorf("config is nil")
	}
	if config.patternExtractor == nil {
		return fmt.Errorf("patternExtractor is nil")
	}

	sb := &strings.Builder{}
	writeFileHeader(sb)

	meta := createLanguageMetadata(config)
	writeSectionHeader(sb, "Language metadata")

	data, err := yaml.Dump(&meta, yaml.WithIndent(2))
	if err != nil {
		return fmt.Errorf("could not encode syntax file: %w", err)
	}
	sb.Write(data)
	sb.WriteString("\n")

	writeSectionHeader(sb, "Contexts and rules")

	contexts := buildContexts(config)
	if err := writeContexts(sb, contexts); err != nil {
		return err
	}

	if err := system.FileWriteString(config.outputFile, sb.String()); err != nil {
		return fmt.Errorf("could not write data to file: %w", err)
	}

	return nil
}

// -------------------------------------------------------- PRIVATE HELPERS

type languageMetadata struct {
	LanguageName   string   `yaml:"name"`
	FileExtensions []string `yaml:"file_extensions"`
	Scope          string   `yaml:"scope"`
}

type sublimeRule struct {
	Match string `yaml:"match,omitempty"`
	Scope string `yaml:"scope,omitempty"`
	Push  string `yaml:"push,omitempty"`
	Pop   bool   `yaml:"pop,omitempty"`
}

type sublimeContexts struct {
	Contexts map[string][]sublimeRule `yaml:"contexts"`
}

func createLanguageMetadata[TToken comparable](configuration *SublimeTextGeneratorConfig[TToken]) languageMetadata {
	return languageMetadata{
		LanguageName:   configuration.languageName,
		FileExtensions: configuration.fileExtensions,
		Scope:          configuration.scope,
	}
}

func writeFileHeader(sb *strings.Builder) {
	sb.WriteString("%YAML 1.2\n---\n\n")
	sb.WriteString("# ==================================================\n")
	sb.WriteString("#  GENERATED BY LangSpec -- DO NOT EDIT MANUALLY\n")
	sb.WriteString("#  DATE: ")
	sb.WriteString(currentDateTimeReadable())
	sb.WriteString("\n")
	sb.WriteString("# ==================================================\n\n")
}

func writeSectionHeader(sb *strings.Builder, title string) {
	sb.WriteString("# --------------------------------------------------\n")
	sb.WriteString("# " + title + "\n")
	sb.WriteString("# --------------------------------------------------\n")
}

/*
buildContexts emits:
- main context with token match rules (scopes)
- optional push rules to named contexts
- for each named context: a pop rule
*/
func buildContexts[TToken comparable](configuration *SublimeTextGeneratorConfig[TToken]) sublimeContexts {
	contextMap := make(map[string][]sublimeRule)

	// Ensure main exists
	contextMap["main"] = []sublimeRule{}

	// --------------------------------------------------
	// 1) Token styles: add to main (ordered)
	// --------------------------------------------------

	styles := make([]editor.TokenStyle[TToken], 0, len(configuration.tokenStyles))
	styles = append(styles, configuration.tokenStyles...)

	// Sublime rule order matters. Apply highest priority first.
	sort.SliceStable(styles, func(i, j int) bool {
		return styles[i].Priority > styles[j].Priority
	})

	for _, style := range styles {
		matchPattern := configuration.patternExtractor(style.Token)
		if matchPattern == "" {
			// No match for this token -> skip (or you can hard error)
			continue
		}

		contextMap["main"] = append(contextMap["main"], sublimeRule{
			Match: matchPattern,
			Scope: style.Scope,
		})
	}

	// --------------------------------------------------
	// 2) Context transitions (optional; single-state typically none)
	// --------------------------------------------------

	for _, ctx := range configuration.contextDefinitions {
		ctxName := ctx.Name
		if ctxName == "" {
			continue
		}

		enterPattern := configuration.patternExtractor(ctx.EnterOn)
		exitPattern := configuration.patternExtractor(ctx.ExitOn)

		if enterPattern == "" || exitPattern == "" {
			// invalid context wiring -> skip (or hard error)
			continue
		}

		// Push rule in main
		contextMap["main"] = append(contextMap["main"], sublimeRule{
			Match: enterPattern,
			Push:  ctxName,
		})

		// Ensure nested context exists
		if _, exists := contextMap[ctxName]; !exists {
			contextMap[ctxName] = []sublimeRule{}
		}

		// Pop rule in nested context
		contextMap[ctxName] = append(contextMap[ctxName], sublimeRule{
			Match: exitPattern,
			Pop:   true,
		})
	}

	return sublimeContexts{Contexts: contextMap}
}

func writeContexts(sb *strings.Builder, ctx sublimeContexts) error {
	data, err := yaml.Dump(&ctx, yaml.WithIndent(2))
	if err != nil {
		return fmt.Errorf("could not encode contexts: %w", err)
	}
	sb.Write(data)
	return nil
}

func currentDateTimeReadable() string {
	return time.Now().Format("2006-01-02 15:04:05 MST")
}
