package sublime

import (
	"cmp"
	"fmt"
	"foundation/system"
	"strings"
	"time"

	"langspec/editor"

	"go.yaml.in/yaml/v4"
)

const headerLine = "# ======================================================\n"
const timeFormat = "2006-01-02 15:04:05 MST"

type ExtractionConfig[TContext any] struct {
	ExtractScope     func(TContext) string
	ExtractMetaScope func(TContext) string
}

type languageMetadata struct {
	Name           string   `yaml:"name"`
	FileExtensions []string `yaml:"file_extensions"`
	Scope          string   `yaml:"scope"`
	Version        int      `yaml:"version"`
}

type contextEntry struct {
	MetaScope      *string        `yaml:"meta_scope,omitempty"`
	Match          *string        `yaml:"match,omitempty"`
	Scope          string         `yaml:"scope,omitempty"`
	Push           any            `yaml:"push,omitempty"`
	Pop            any            `yaml:"pop,omitempty"`
	Set            any            `yaml:"set,omitempty"`
	Captures       map[int]string `yaml:"captures,omitempty"`
	Embed          string         `yaml:"embed,omitempty"`
	EmbedScope     string         `yaml:"embed_scope,omitempty"`
	Escape         *string        `yaml:"escape,omitempty"`
	EscapeCaptures map[int]string `yaml:"escape_captures,omitempty"`
}

type contextsSection struct {
	Contexts map[string][]contextEntry `yaml:"contexts"`
}

func GenerateSyntaxFile[TObservation cmp.Ordered, TToken, TTokenRole, TLexerState, TNodeKind comparable, TContext any](
	ir *editor.EditorIR[TObservation, TToken, TTokenRole, TLexerState, TNodeKind, TContext],
	fileExtensions []string,
	baseScope string,
	outputFile string,
	config ExtractionConfig[TContext],
) error {
	sb := &strings.Builder{}

	writeHeader(sb, ir.LanguageName, ir.LanguageVersion)

	if err := writeMetadata(sb, ir.LanguageName, fileExtensions, baseScope); err != nil {
		return err
	}

	if err := writeContexts(sb, ir.LanguageMachine, config); err != nil {
		return err
	}

	if err := system.FileWriteString(outputFile, sb.String()); err != nil {
		return fmt.Errorf("could not write definition to file: %w", err)
	}

	return nil
}

func writeHeader(sb *strings.Builder, name, version string) {
	sb.WriteString("%YAML 1.2\n---\n\n")
	sb.WriteString(headerLine)
	sb.WriteString("#  GENERATED BY LangSpec -- DO NOT EDIT MANUALLY\n")
	sb.WriteString(headerLine)
	fmt.Fprintf(sb, "#  DATE: %s\n", time.Now().Format(timeFormat))
	fmt.Fprintf(sb, "#  GENERATED FOR: %s @ %s\n", name, version)
	sb.WriteString(headerLine)
	sb.WriteString("\n")
}

func writeSectionHeader(sb *strings.Builder, headerContent string) {
	sb.WriteString(headerLine)
	fmt.Fprintf(sb, "#  %s\n", headerContent)
	sb.WriteString(headerLine)
}

func writeMetadata(sb *strings.Builder, name string, exts []string, baseScope string) error {
	writeSectionHeader(sb, "Language Metadata")
	meta := languageMetadata{
		Name:           name,
		FileExtensions: exts,
		Scope:          baseScope,
		Version:        2,
	}
	return encodeAndWriteYAML(sb, meta)
}

func writeContexts[TObservation cmp.Ordered, TContext any](
	sb *strings.Builder,
	machine editor.LanguageMachine[TObservation, TContext],
	config ExtractionConfig[TContext],
) error {
	writeSectionHeader(sb, "Contexts & Rules")
	contextsMap := buildContextsMap(machine, config)
	section := contextsSection{Contexts: contextsMap}
	return encodeAndWriteYAML(sb, section)
}

func buildContextsMap[TObservation cmp.Ordered, TContext any](
	machine editor.LanguageMachine[TObservation, TContext],
	config ExtractionConfig[TContext],
) map[string][]contextEntry {
	contextsMap := make(map[string][]contextEntry)

	for _, state := range machine.EditorStates {
		label := determineContextLabel(state.Label)
		entries := buildTransitions(state.Transitions, config)
		entries = processMetaScope(state, entries, config)
		contextsMap[label] = entries
	}

	if len(machine.AmbientTransitions) > 0 {
		contextsMap["prototype"] = buildTransitions(machine.AmbientTransitions, config)
	}

	return contextsMap
}

func processMetaScope[TObservation cmp.Ordered, TContext any](
	state editor.EditorState[TObservation, TContext],
	entries []contextEntry,
	config ExtractionConfig[TContext],
) []contextEntry {
	if metaScope := config.ExtractMetaScope(state.Context); metaScope != "" {
		metaEntry := contextEntry{MetaScope: &metaScope}
		return append([]contextEntry{metaEntry}, entries...)
	}
	return entries
}

func buildTransitions[TObservation cmp.Ordered, TContext any](
	transitions []editor.EditorTransition[TObservation, TContext],
	config ExtractionConfig[TContext],
) []contextEntry {
	var entries []contextEntry
	for _, t := range transitions {
		entries = append(entries, buildSingleTransition(t, config))
	}
	return entries
}

func buildSingleTransition[TObservation cmp.Ordered, TContext any](
	t editor.EditorTransition[TObservation, TContext],
	config ExtractionConfig[TContext],
) contextEntry {
	regexStr, err := t.OnPattern.ToRegEx()
	if err != nil {
		panic(fmt.Errorf("engine error encountered while converting pattern to RegEx: %w", err))
	}

	if t.IsLookahead {
		regexStr = fmt.Sprintf("(?=%s)", regexStr)
	}

	entry := contextEntry{
		Match:    &regexStr,
		Scope:    config.ExtractScope(t.MatchContext),
		Captures: buildCapturesMap(t.Captures, config.ExtractScope),
	}

	applyStackOperation(&entry, t, config)
	return entry
}

func buildCapturesMap[TContext any](
	captures map[int]TContext,
	extractScope func(TContext) string,
) map[int]string {
	if len(captures) == 0 {
		return nil
	}

	mapped := make(map[int]string, len(captures))
	for index, ctx := range captures {
		mapped[index] = extractScope(ctx)
	}
	return mapped
}

func applyStackOperation[TObservation cmp.Ordered, TContext any](
	entry *contextEntry,
	t editor.EditorTransition[TObservation, TContext],
	config ExtractionConfig[TContext],
) {
	switch t.Operation {
	case editor.STACK_PUSH:
		entry.Push = determineContextLabels(t.Targets)
	case editor.STACK_POP:
		entry.Pop = t.PopAmount
	case editor.STACK_SET:
		entry.Set = determineContextLabels(t.Targets)
	case editor.STACK_EMBED:
		applyEmbedOperation(entry, t.ForeignPayload, config)
	case editor.STACK_NONE:
	}
}

func applyEmbedOperation[TObservation cmp.Ordered, TContext any](
	entry *contextEntry,
	payload *editor.ForeignMachinePayload[TObservation, TContext],
	config ExtractionConfig[TContext],
) {
	if payload == nil {
		return
	}

	escapeStr, err := payload.EscapePattern.ToRegEx()
	if err != nil {
		panic(fmt.Errorf("failed to compile escape pattern: %w", err))
	}

	entry.Embed = payload.MachineID
	entry.EmbedScope = config.ExtractMetaScope(payload.MachineContext)
	entry.Escape = &escapeStr
	entry.EscapeCaptures = buildCapturesMap(payload.EscapeCaptures, config.ExtractScope)
}

func determineContextLabels[TObservation cmp.Ordered, TContext any](targets []*editor.EditorState[TObservation, TContext]) []string {
	out := make([]string, len(targets))
	for i, target := range targets {
		out[i] = determineContextLabel(target.Label)
	}
	return out
}

func determineContextLabel(label string) string {
	if label == editor.ROOT_LABEL {
		return "main"
	}
	return label
}

func encodeAndWriteYAML(sb *strings.Builder, data any) error {
	value, err := yaml.Marshal(data)
	if err != nil {
		return fmt.Errorf("yaml marshal failed: %w", err)
	}
	sb.Write(value)
	sb.WriteString("\n")
	return nil
}
