package sublime

import (
	"cmp"
	"fmt"
	"foundation/system"
	"strings"
	"time"

	"langspec/editor"

	"go.yaml.in/yaml/v4"
)

const headerLine = "# ======================================================\n"
const timeFormat = "2006-01-02 15:04:05 MST"

// ------------------------------------------------------------------ TYPES

// ExtractionConfig centralizes all generic context unpacking logic.
type ExtractionConfig[TContext any] struct {
	ExtractScope     func(TContext) string
	ExtractMetaScope func(TContext) string
}

type languageMetadata struct {
	Name           string   `yaml:"name"`
	FileExtensions []string `yaml:"file_extensions"`
	Scope          string   `yaml:"scope"`
	Version        int      `yaml:"version"`
}

type contextEntry struct {
	MetaScope      *string        `yaml:"meta_scope,omitempty"`
	Match          *string        `yaml:"match,omitempty"`
	Scope          string         `yaml:"scope,omitempty"`
	Push           any            `yaml:"push,omitempty"`
	Pop            any            `yaml:"pop,omitempty"`
	Set            any            `yaml:"set,omitempty"`
	Captures       map[int]string `yaml:"captures,omitempty"`
	Embed          string         `yaml:"embed,omitempty"`
	EmbedScope     string         `yaml:"embed_scope,omitempty"`
	Escape         *string        `yaml:"escape,omitempty"`
	EscapeCaptures map[int]string `yaml:"escape_captures,omitempty"`
}

type contextsSection struct {
	Contexts map[string][]contextEntry `yaml:"contexts"`
}

// ------------------------------------------------------------------ PUBLIC API

func GenerateSyntaxFile[TObservation cmp.Ordered, TToken, TTokenRole, TLexerState, TNodeKind comparable, TContext any](
	ir *editor.EditorIR[TObservation, TToken, TTokenRole, TLexerState, TNodeKind, TContext],
	fileExtensions []string,
	baseScope string,
	outputFile string,
	config ExtractionConfig[TContext],
) error {
	sb := &strings.Builder{}

	writeHeader(sb, ir.LanguageName, ir.LanguageVersion)

	if err := writeMetadata(sb, ir.LanguageName, fileExtensions, baseScope); err != nil {
		return err
	}

	// Pass the entire LanguageMachine instead of just the EditorStates
	if err := writeContexts(sb, ir.LanguageMachine, config); err != nil {
		return err
	}

	if err := system.FileWriteString(outputFile, sb.String()); err != nil {
		return fmt.Errorf("could not write definition to file: %w", err)
	}

	return nil
}

// ------------------------------------------------------------------ SECTIONS

func writeHeader(sb *strings.Builder, name, version string) {
	sb.WriteString("%YAML 1.2\n---\n\n")
	sb.WriteString(headerLine)
	sb.WriteString("#  GENERATED BY LangSpec -- DO NOT EDIT MANUALLY\n")
	sb.WriteString(headerLine)
	fmt.Fprintf(sb, "#  DATE: %s\n", time.Now().Format(timeFormat))
	fmt.Fprintf(sb, "#  GENERATED FOR: %s @ %s\n", name, version)
	sb.WriteString(headerLine)
	sb.WriteString("\n")
}

func writeSectionHeader(sb *strings.Builder, headerContent string) {
	sb.WriteString(headerLine)
	fmt.Fprintf(sb, "#  %s\n", headerContent)
	sb.WriteString(headerLine)
}

func writeMetadata(sb *strings.Builder, name string, exts []string, baseScope string) error {
	writeSectionHeader(sb, "Language Metadata")

	meta := languageMetadata{
		Name:           name,
		FileExtensions: exts,
		Scope:          baseScope,
		Version:        2,
	}

	return encodeAndWriteYAML(sb, meta)
}

func writeContexts[TObservation cmp.Ordered, TContext any](
	sb *strings.Builder,
	machine editor.LanguageMachine[TObservation, TContext],
	config ExtractionConfig[TContext],
) error {
	writeSectionHeader(sb, "Contexts & Rules")

	contextsMap := buildContextsMap(machine, config)
	section := contextsSection{Contexts: contextsMap}

	return encodeAndWriteYAML(sb, section)
}

// ------------------------------------------------------------------ BUILDERS

func buildContextsMap[TObservation cmp.Ordered, TContext any](
	machine editor.LanguageMachine[TObservation, TContext],
	config ExtractionConfig[TContext],
) map[string][]contextEntry {

	contextsMap := make(map[string][]contextEntry)

	// Map structural PDA states to Sublime Contexts
	for _, state := range machine.EditorStates {
		label := determineContextLabel(state.Label)
		entries := buildTransitions(state.Transitions, config)

		if metaScope := config.ExtractMetaScope(state.Context); metaScope != "" {
			metaEntry := contextEntry{MetaScope: &metaScope}
			entries = append([]contextEntry{metaEntry}, entries...)
		}

		// HasFallthroughPop: afterNest continuation contexts must eventually pop even
		// when their optional tail tokens (e.g. ';') are absent. A lookahead-POP rule
		// "(?=\S) → pop: 1" fires on any non-whitespace character that no earlier rule
		// consumed, causing the context to exit cleanly rather than getting stuck.
		if state.HasFallthroughPop {
			entries = append(entries, fallthroughPopEntry())
		}

		contextsMap[label] = entries
	}

	// Map ambient transitions into Sublime's native prototype context
	if len(machine.AmbientTransitions) > 0 {
		contextsMap["prototype"] = buildTransitions(machine.AmbientTransitions, config)
	}

	return contextsMap
}

func buildTransitions[TObservation cmp.Ordered, TContext any](
	transitions []editor.EditorTransition[TObservation, TContext],
	config ExtractionConfig[TContext],
) []contextEntry {

	var entries []contextEntry

	for _, t := range transitions {
		entry := buildSingleTransition(t, config)
		entries = append(entries, entry)
	}

	return entries
}

func buildSingleTransition[TObservation cmp.Ordered, TContext any](
	t editor.EditorTransition[TObservation, TContext],
	config ExtractionConfig[TContext],
) contextEntry {

	regexStr, err := t.OnPattern.ToRegEx()
	if err != nil {
		panic(fmt.Errorf("engine error encountered while converting pattern to RegEx: %w", err))
	}

	if t.IsLookahead {
		regexStr = fmt.Sprintf("(?=%s)", regexStr)
	}

	entry := contextEntry{
		Match:    &regexStr,
		Scope:    config.ExtractScope(t.MatchContext),
		Captures: buildCapturesMap(t.Captures, config.ExtractScope),
	}

	applyStackOperation(&entry, t, config)

	return entry
}

func buildCapturesMap[TContext any](
	captures map[int]TContext,
	extractScope func(TContext) string,
) map[int]string {
	if len(captures) == 0 {
		return nil
	}

	mapped := make(map[int]string, len(captures))
	for index, ctx := range captures {
		mapped[index] = extractScope(ctx)
	}

	return mapped
}

// ------------------------------------------------------------------ UTILS

func applyStackOperation[TObservation cmp.Ordered, TContext any](
	entry *contextEntry,
	t editor.EditorTransition[TObservation, TContext],
	config ExtractionConfig[TContext],
) {
	switch t.Operation {
	case editor.STACK_PUSH:
		entry.Push = determineContextLabels(t.Targets)
	case editor.STACK_POP:
		entry.Pop = t.PopAmount
	case editor.STACK_SET:
		entry.Set = determineContextLabels(t.Targets)
	case editor.STACK_EMBED:
		applyEmbedOperation(entry, t.ForeignPayload, config)
	case editor.STACK_NONE:
		// Transition consumes the token and applies scope without altering the stack.
	}
}

func applyEmbedOperation[TObservation cmp.Ordered, TContext any](
	entry *contextEntry,
	payload *editor.ForeignMachinePayload[TObservation, TContext],
	config ExtractionConfig[TContext],
) {
	if payload == nil {
		return
	}

	escapeStr, err := payload.EscapePattern.ToRegEx()
	if err != nil {
		panic(fmt.Errorf("failed to compile escape pattern: %w", err))
	}

	entry.Embed = payload.MachineID
	entry.EmbedScope = config.ExtractMetaScope(payload.MachineContext)
	entry.Escape = &escapeStr
	entry.EscapeCaptures = buildCapturesMap(payload.EscapeCaptures, config.ExtractScope)
}

// fallthroughPopEntry returns the last-resort context entry that pops the current
// Sublime context when no earlier match rule fires. It uses a zero-width lookahead
// for any non-whitespace character ("(?=\S)") so that the context exits without
// consuming the character, letting the parent context re-process it.
// This is only attached to afterNest continuation contexts (HasFallthroughPop=true)
// that would otherwise stay on the stack indefinitely when their optional tail tokens
// (e.g. ';') are absent.
func fallthroughPopEntry() contextEntry {
	regex := `(?=\S)`
	return contextEntry{
		Match: &regex,
		Pop:   1,
	}
}

func determineContextLabels[TObservation cmp.Ordered, TContext any](targets []*editor.EditorState[TObservation, TContext]) []string {
	out := make([]string, len(targets))

	for i, target := range targets {
		out[i] = determineContextLabel(target.Label)
	}

	return out
}

func determineContextLabel(label string) string {
	if label == editor.ROOT_LABEL {
		return "main"
	}
	return label
}

func encodeAndWriteYAML(sb *strings.Builder, data any) error {
	value, err := yaml.Marshal(data)
	if err != nil {
		return fmt.Errorf("yaml marshal failed: %w", err)
	}

	sb.Write(value)
	sb.WriteString("\n")
	return nil
}
