package sublime

import (
	"cmp"
	"fmt"
	"foundation/system"
	"sort"
	"strings"
	"time"

	"langspec/editor"

	"go.yaml.in/yaml/v4"
)

const headerLine = "# ======================================================\n"
const timeFormat = "2006-01-02 15:04:05 MST"

type ExtractionConfig[TContext any] struct {
	ExtractScope     func(TContext) string
	ExtractMetaScope func(TContext) string
}

type languageMetadata struct {
	Name           string   `yaml:"name"`
	FileExtensions []string `yaml:"file_extensions"`
	Scope          string   `yaml:"scope"`
	Version        int      `yaml:"version"`
}

type contextEntry struct {
	MetaScope      *string        `yaml:"meta_scope,omitempty"`
	Match          *string        `yaml:"match,omitempty"`
	Scope          string         `yaml:"scope,omitempty"`
	Push           any            `yaml:"push,omitempty"`
	Pop            any            `yaml:"pop,omitempty"`
	Set            any            `yaml:"set,omitempty"`
	Captures       map[int]string `yaml:"captures,omitempty"`
	Embed          string         `yaml:"embed,omitempty"`
	EmbedScope     string         `yaml:"embed_scope,omitempty"`
	Escape         *string        `yaml:"escape,omitempty"`
	EscapeCaptures map[int]string `yaml:"escape_captures,omitempty"`
	Include        *string        `yaml:"include,omitempty"`
}

type contextsSection struct {
	Contexts map[string][]contextEntry `yaml:"contexts"`
}

func GenerateSyntaxFile[TObservation cmp.Ordered, TToken, TTokenRole, TLexerState, TNodeKind comparable, TContext any](
	ir *editor.EditorIR[TObservation, TToken, TTokenRole, TLexerState, TNodeKind, TContext],
	fileExtensions []string,
	baseScope string,
	outputFile string,
	config ExtractionConfig[TContext],
) error {
	sb := &strings.Builder{}

	writeHeader(sb, ir.LanguageName, ir.LanguageVersion)

	if err := writeMetadata(sb, ir.LanguageName, fileExtensions, baseScope); err != nil {
		return err
	}

	if err := writeContexts(sb, ir.LanguageMachine, config); err != nil {
		return err
	}

	if err := system.FileWriteString(outputFile, sb.String()); err != nil {
		return fmt.Errorf("could not write definition to file: %w", err)
	}

	return nil
}

func writeHeader(sb *strings.Builder, name, version string) {
	sb.WriteString("%YAML 1.2\n---\n\n")
	sb.WriteString(headerLine)
	sb.WriteString("#  GENERATED BY LangSpec -- DO NOT EDIT MANUALLY\n")
	sb.WriteString(headerLine)
	fmt.Fprintf(sb, "#  DATE: %s\n", time.Now().Format(timeFormat))
	fmt.Fprintf(sb, "#  GENERATED FOR: %s @ %s\n", name, version)
	sb.WriteString(headerLine)
	sb.WriteString("\n")
}

func writeSectionHeader(sb *strings.Builder, headerContent string) {
	sb.WriteString(headerLine)
	fmt.Fprintf(sb, "#  %s\n", headerContent)
	sb.WriteString(headerLine)
}

func writeMetadata(sb *strings.Builder, name string, exts []string, baseScope string) error {
	writeSectionHeader(sb, "Language Metadata")
	meta := languageMetadata{
		Name:           name,
		FileExtensions: exts,
		Scope:          baseScope,
		Version:        2,
	}
	return encodeAndWriteYAML(sb, meta)
}

func writeContexts[TObservation cmp.Ordered, TContext any](
	sb *strings.Builder,
	machine editor.LanguageMachine[TObservation, TContext],
	config ExtractionConfig[TContext],
) error {
	writeSectionHeader(sb, "Contexts & Rules")
	contextsMap := buildContextsMap(machine, config)
	section := contextsSection{Contexts: contextsMap}
	return encodeAndWriteYAML(sb, section)
}

func buildContextsMap[TObservation cmp.Ordered, TContext any](
	machine editor.LanguageMachine[TObservation, TContext],
	config ExtractionConfig[TContext],
) map[string][]contextEntry {
	contextsMap := make(map[string][]contextEntry)

	stateBaseEntries := make(map[string][]contextEntry)
	stateSignatures := make(map[string]string)
	sigCounts := make(map[string]int)

	// PASS 1: Generate base entries (the raw regex matches) and build signatures
	for _, state := range machine.EditorStates {
		label := determineContextLabel(state.Label)
		baseEntries := buildTransitions(state.Transitions, config)
		stateBaseEntries[label] = baseEntries

		// We only compress blocks with 2 or more transitions to avoid overhead
		if len(baseEntries) > 1 {
			sig := generateEntriesSignature(baseEntries)
			stateSignatures[label] = sig
			sigCounts[sig]++
		}
	}

	// PASS 2: Deterministically assign shared context names to duplicates
	sharedGroups := make(map[string]string) // signature -> shared_name
	sharedPool := make(map[string][]contextEntry)
	sharedCounter := 0

	for _, state := range machine.EditorStates {
		label := determineContextLabel(state.Label)
		sig, hasSig := stateSignatures[label]

		if hasSig && sigCounts[sig] > 1 {
			if _, alreadyCreated := sharedGroups[sig]; !alreadyCreated {
				sharedName := fmt.Sprintf("shared_%d", sharedCounter)
				sharedCounter++
				sharedGroups[sig] = sharedName
				sharedPool[sharedName] = stateBaseEntries[label]
			}
		}
	}

	// PASS 3: Apply the includes, then re-attach the structural wrappers (Push/Pop/MetaScope)
	for _, state := range machine.EditorStates {
		label := determineContextLabel(state.Label)
		baseEntries := stateBaseEntries[label]

		// Swap raw transitions for an include pointer if it belongs to a shared group
		if sig, hasSig := stateSignatures[label]; hasSig && sigCounts[sig] > 1 {
			sharedName := sharedGroups[sig]
			baseEntries = []contextEntry{{Include: stringPtr(sharedName)}}
		}

		// Now apply the editor-specific wrapper mechanics around the base logic
		if state.ImmediatePushTarget != nil {
			baseEntries = append(baseEntries, contextEntry{
				Match: stringPtr(`(?=[\s\S]*)`),
				Push:  []string{determineContextLabel(state.ImmediatePushTarget.Label)},
			})
		}

		if metaScope := config.ExtractMetaScope(state.Context); metaScope != "" {
			metaEntry := contextEntry{MetaScope: &metaScope}
			baseEntries = append([]contextEntry{metaEntry}, baseEntries...)
		}

		if state.HasFallthroughPop {
			popAmount := 1
			if state.FallthroughPopAmount > 0 {
				popAmount = state.FallthroughPopAmount
			}
			baseEntries = append(baseEntries, contextEntry{
				Match: stringPtr(`(?=\S)`),
				Pop:   popAmount,
			})
		}

		contextsMap[label] = baseEntries
	}

	// Merge the shared transition blocks into the final output
	for sharedName, entries := range sharedPool {
		contextsMap[sharedName] = entries
	}

	if len(machine.AmbientTransitions) > 0 {
		contextsMap["prototype"] = buildTransitions(machine.AmbientTransitions, config)
	}

	return contextsMap
}

func generateEntriesSignature(entries []contextEntry) string {
	var sb strings.Builder
	for _, e := range entries {
		if e.Match != nil {
			sb.WriteString(*e.Match)
		}
		sb.WriteString("||")
		sb.WriteString(e.Scope)
		sb.WriteString("||")

		// Serialize Stack Ops
		fmt.Fprintf(&sb, "P%v:O%v:S%v||", e.Push, e.Pop, e.Set)

		// Serialize Captures Deterministically
		if len(e.Captures) > 0 {
			keys := make([]int, 0, len(e.Captures))
			for k := range e.Captures {
				keys = append(keys, k)
			}
			sort.Ints(keys)
			for _, k := range keys {
				fmt.Fprintf(&sb, "%d:%s,", k, e.Captures[k])
			}
		}
		sb.WriteString("||")

		// Serialize Embeds
		sb.WriteString(e.Embed)
		sb.WriteString("||")
		if e.Escape != nil {
			sb.WriteString(*e.Escape)
		}
		sb.WriteString("###")
	}
	return sb.String()
}

// Helper to easily get a pointer to a string literal
func stringPtr(s string) *string {
	return &s
}

func processMetaScope[TObservation cmp.Ordered, TContext any](
	state editor.EditorState[TObservation, TContext],
	entries []contextEntry,
	config ExtractionConfig[TContext],
) []contextEntry {
	if metaScope := config.ExtractMetaScope(state.Context); metaScope != "" {
		metaEntry := contextEntry{MetaScope: &metaScope}
		return append([]contextEntry{metaEntry}, entries...)
	}
	return entries
}

func buildTransitions[TObservation cmp.Ordered, TContext any](
	transitions []editor.EditorTransition[TObservation, TContext],
	config ExtractionConfig[TContext],
) []contextEntry {
	var entries []contextEntry
	for _, t := range transitions {
		entries = append(entries, buildSingleTransition(t, config))
	}
	return entries
}

func buildSingleTransition[TObservation cmp.Ordered, TContext any](
	t editor.EditorTransition[TObservation, TContext],
	config ExtractionConfig[TContext],
) contextEntry {
	regexStr, err := t.OnPattern.ToRegEx()
	if err != nil {
		panic(fmt.Errorf("engine error encountered while converting pattern to RegEx: %w", err))
	}

	if t.IsLookahead {
		regexStr = fmt.Sprintf("(?=%s)", regexStr)
	}

	entry := contextEntry{
		Match:    &regexStr,
		Scope:    config.ExtractScope(t.MatchContext),
		Captures: buildCapturesMap(t.Captures, config.ExtractScope),
	}

	applyStackOperation(&entry, t, config)
	return entry
}

func buildCapturesMap[TContext any](
	captures map[int]TContext,
	extractScope func(TContext) string,
) map[int]string {
	if len(captures) == 0 {
		return nil
	}

	mapped := make(map[int]string, len(captures))
	for index, ctx := range captures {
		mapped[index] = extractScope(ctx)
	}
	return mapped
}

func applyStackOperation[TObservation cmp.Ordered, TContext any](
	entry *contextEntry,
	t editor.EditorTransition[TObservation, TContext],
	config ExtractionConfig[TContext],
) {
	switch t.Operation {
	case editor.STACK_PUSH:
		entry.Push = determineContextLabels(t.Targets)
	case editor.STACK_POP:
		entry.Pop = t.PopAmount
	case editor.STACK_SET:
		entry.Set = determineContextLabels(t.Targets)
	case editor.STACK_EMBED:
		applyEmbedOperation(entry, t.ForeignPayload, config)
	case editor.STACK_NONE:
	}
}

func applyEmbedOperation[TObservation cmp.Ordered, TContext any](
	entry *contextEntry,
	payload *editor.ForeignMachinePayload[TObservation, TContext],
	config ExtractionConfig[TContext],
) {
	if payload == nil {
		return
	}

	escapeStr, err := payload.EscapePattern.ToRegEx()
	if err != nil {
		panic(fmt.Errorf("failed to compile escape pattern: %w", err))
	}

	entry.Embed = payload.MachineID
	entry.EmbedScope = config.ExtractMetaScope(payload.MachineContext)
	entry.Escape = &escapeStr
	entry.EscapeCaptures = buildCapturesMap(payload.EscapeCaptures, config.ExtractScope)
}

func determineContextLabels[TObservation cmp.Ordered, TContext any](targets []*editor.EditorState[TObservation, TContext]) []string {
	out := make([]string, len(targets))
	for i, target := range targets {
		out[i] = determineContextLabel(target.Label)
	}
	return out
}

func determineContextLabel(label string) string {
	if label == editor.ROOT_LABEL {
		return "main"
	}
	return label
}

func encodeAndWriteYAML(sb *strings.Builder, data any) error {
	value, err := yaml.Marshal(data)
	if err != nil {
		return fmt.Errorf("yaml marshal failed: %w", err)
	}
	sb.Write(value)
	sb.WriteString("\n")
	return nil
}
