package toolchain

import (
	"fmt"
	"foundation/system"
	"langspec/dsl"
	"strconv"
	"strings"
)

// PRAGMA keys for the go_bindings toolchain (tool.go_bindings { ... } in .lspec).
const (
	GoBindingsToolName           = "go_bindings"
	GoBindingsOutputPathKey      = "output-path"
	GoBindingsPackageNameKey     = "package-name"
	GoBindingsNamespacePrefixKey = "namespace-prefix"
	GoBindingsEnableKey          = "enable"
)

/*
RunGoBindingsToolchain generates a Go source file with strongly-typed Token and
Node types and one const per lexical token and per grammar node from the compiled
spec. The generated file is written to the path and package specified in the
tool.go_bindings PRAGMA.

Use cases:
- Type-safe AST handling in downstream compilers (e.g. validation, codegen) without magic strings.
- Sharing token and node identity across packages that consume the same .lspec (import the generated package).
- Enabling switch/map keyed by Token or Node with compile-time exhaustiveness where applicable.

Prerequisites:
- compileResult must be a valid LangSpecCompileResult from a successful compile.
- The .lspec must contain a tool.go_bindings PRAGMA with enable = true, output-path, and package-name set.
- Relative output-path is resolved against cwd and ancestors (see resolveGoBindingsOutputPath) so repo-root paths like src/compiler/foo.go work when the generator runs from src/compiler.

Edge cases:
- Returns nil without error if no tool.go_bindings PRAGMA is present or enable is not "true".
- If the spec has no tokens (resp. no nodes), the generated file omits the Token (resp. Node) type and const block.
- Returns an error if output-path or package-name is missing when the toolchain is enabled.
*/
func RunGoBindingsToolchain(compileResult *dsl.LangSpecCompileResult) error {
	for _, pragma := range compileResult.CompiledToolPragmas {
		if pragma.ToolName == GoBindingsToolName {
			return processGoBindingsPragma(compileResult, pragma)
		}
	}
	return nil
}

func processGoBindingsPragma(compileResult *dsl.LangSpecCompileResult, pragma dsl.ToolPragma) error {
	// 1. Validate Enablement safely
	enabled, ok := pragma.Settings[GoBindingsEnableKey].(string)
	if !ok || enabled == "false" {
		return nil // Not enabled or missing (defaults to off)
	}
	if enabled != "true" {
		return fmt.Errorf("go_bindings: unexpected '%s' value: '%v'", GoBindingsEnableKey, pragma.Settings[GoBindingsEnableKey])
	}

	// 2. Validate Output Path
	outputPath, ok := pragma.Settings[GoBindingsOutputPathKey].(string)
	if !ok || strings.TrimSpace(outputPath) == "" {
		return fmt.Errorf("go_bindings toolchain enabled but missing or invalid '%s'", GoBindingsOutputPathKey)
	}

	// 3. Validate Package Name
	packageName, ok := pragma.Settings[GoBindingsPackageNameKey].(string)
	if !ok || strings.TrimSpace(packageName) == "" {
		return fmt.Errorf("go_bindings toolchain enabled but missing or invalid '%s'", GoBindingsPackageNameKey)
	}

	// 4. Extract Optional Namespace Prefix
	var typePrefix *string
	if prefix, hasPrefix := pragma.Settings[GoBindingsNamespacePrefixKey].(string); hasPrefix && strings.TrimSpace(prefix) != "" {
		typePrefix = &prefix
	}

	// 5. Resolve Path and Execute
	resolved, err := system.PathResolveWorkspace(outputPath)
	if err != nil {
		return fmt.Errorf("go_bindings path resolution failed for '%s': %w", outputPath, err)
	}

	return executeGoBindingsToolchain(compileResult, resolved, packageName, typePrefix)
}

func executeGoBindingsToolchain(
	compileResult *dsl.LangSpecCompileResult,
	outputPath string,
	packageName string,
	typePrefix *string,
) error {
	sym := compileResult.CompiledSymbols
	if sym == nil {
		return fmt.Errorf("go_bindings: compiled symbols missing on compile result")
	}

	tokens := sym.TokenNames()
	nodes := sym.NodeKindNames()

	prefix := ""
	if typePrefix != nil {
		prefix = *typePrefix
	}

	sourceCode := generateBindingsCode(packageName, prefix, tokens, nodes)

	if err := system.FileWriteString(outputPath, sourceCode); err != nil {
		return fmt.Errorf("failed to write go bindings file: %w", err)
	}

	return nil
}

func generateBindingsCode(packageName string, prefix string, tokens []string, nodes []string) string {
	var sb strings.Builder
	sb.WriteString("// Code generated by LangSpec. DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	if len(tokens)+len(nodes) > 0 {
		sb.WriteString("import \"strconv\"\n\n")
	}

	writeUint32TypeBlock(&sb, prefix, "Token", tokens, 2)
	writeUint32TypeBlock(&sb, prefix, "Node", nodes, 1)

	return strings.TrimSpace(sb.String()) + "\n"
}

func writeUint32TypeBlock(sb *strings.Builder, prefix string, kind string, items []string, startID int) {
	if len(items) == 0 {
		return
	}

	typeName := prefix + kind
	tableVar := kind + "Names"
	if prefix != "" {
		tableVar = prefix + kind + "Names"
	}

	sb.WriteString(fmt.Sprintf("// %s represents a %s generated by LangSpec (IDs match compiler symbol table).\n", typeName, kind))
	sb.WriteString(fmt.Sprintf("type %s uint32\n\n", typeName))
	sb.WriteString("const (\n")

	for i, item := range items {
		id := startID + i
		constName := item
		if prefix != "" {
			constName = fmt.Sprintf("%s_%s", prefix, item)
		}
		sb.WriteString(fmt.Sprintf("\t%s %s = %d\n", constName, typeName, id))
	}

	sb.WriteString(")\n\n")

	sb.WriteString(fmt.Sprintf("var %s = [...]string{\n", tableVar))
	for _, item := range items {
		sb.WriteString("\t" + strconv.Quote(item) + ",\n")
	}
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("func (t %s) String() string {\n", typeName))
	sb.WriteString("\tif t < " + strconv.Itoa(startID) + " || int(t-" + strconv.Itoa(startID) + ") >= len(" + tableVar + ") {\n")
	sb.WriteString("\t\treturn \"" + typeName + "(\" + strconv.FormatUint(uint64(t), 10) + \")\"\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn " + tableVar + "[t-" + strconv.Itoa(startID) + "]\n")
	sb.WriteString("}\n\n")
}
