package toolchain

import (
	"fmt"
	"foundation/system"
	"langspec/dsl"
	"sort"
	"strings"
	"syntaxa"
)

// PRAGMA keys for the go_bindings toolchain (tool.go_bindings { ... } in .lspec).
const (
	GoBindingsToolName       = "go_bindings"
	GoBindingsOutputPathKey  = "output-path"
	GoBindingsPackageNameKey = "package-name"
	GoBindingsEnableKey      = "enable"
)

/*
RunGoBindingsToolchain generates a Go source file with strongly-typed Token and
Node types and one const per lexical token and per grammar node from the compiled
spec. The generated file is written to the path and package specified in the
tool.go_bindings PRAGMA.

Use cases:
- Type-safe AST handling in downstream compilers (e.g. validation, codegen) without magic strings.
- Sharing token and node identity across packages that consume the same .lspec (import the generated package).
- Enabling switch/map keyed by Token or Node with compile-time exhaustiveness where applicable.

Prerequisites:
- compileResult must be a valid LangSpecCompileResult from a successful compile.
- The .lspec must contain a tool.go_bindings PRAGMA with enable = true, output-path, and package-name set.
- Relative output-path is resolved against cwd and ancestors (see resolveGoBindingsOutputPath) so repo-root paths like src/compiler/foo.go work when the generator runs from src/compiler.

Edge cases:
- Returns nil without error if no tool.go_bindings PRAGMA is present or enable is not "true".
- If the spec has no tokens (resp. no nodes), the generated file omits the Token (resp. Node) type and const block.
- Returns an error if output-path or package-name is missing when the toolchain is enabled.
*/
func RunGoBindingsToolchain(compileResult *dsl.LangSpecCompileResult) error {
	for _, pragma := range compileResult.CompiledToolPragmas {
		if pragma.ToolName != GoBindingsToolName {
			continue
		}

		enabled := pragma.Settings[GoBindingsEnableKey]
		if enabled == "false" {
			return nil
		}
		if enabled != "true" {
			return fmt.Errorf("unexpected enabled setting value: '%s'", enabled)
		}

		outputPath := pragma.Settings[GoBindingsOutputPathKey].(string)
		packageName := pragma.Settings[GoBindingsPackageNameKey].(string)

		if outputPath == "" {
			return fmt.Errorf("go_bindings toolchain enabled but missing 'output-path'")
		}
		if packageName == "" {
			return fmt.Errorf("go_bindings toolchain enabled but missing 'package-name'")
		}

		resolved, err := system.PathResolveWorkspace(outputPath)
		if err != nil {
			return fmt.Errorf("go_bindings output-path: %w", err)
		}

		return executeGoBindingsToolchain(compileResult, resolved, packageName)
	}
	return nil
}

func executeGoBindingsToolchain(
	compileResult *dsl.LangSpecCompileResult,
	outputPath string,
	packageName string,
) error {
	// 1. Collect Unique Tokens
	tokenSet := make(map[string]bool)
	ruleset := compileResult.CompiledLexerSpec.Ruleset("default")
	for _, rule := range ruleset.GetRules() {
		tokenStr := fmt.Sprintf("%v", rule.Token)
		if tokenStr != "" {
			tokenSet[tokenStr] = true
		}
	}

	// 2. Collect Unique Nodes
	nodeSet := make(map[string]bool)
	seen := make(map[interface{}]bool)
	for _, g := range compileResult.CompiledGrammarPackage.Grammars {
		collectNodes(g, nodeSet, seen)
	}

	// 3. Sort alphabetically for deterministic output
	var tokens []string
	for t := range tokenSet {
		tokens = append(tokens, t)
	}
	sort.Strings(tokens)

	var nodes []string
	for n := range nodeSet {
		nodes = append(nodes, n)
	}
	sort.Strings(nodes)

	// 4. Render the Go Code
	var sb strings.Builder
	sb.WriteString("// Code generated by LangSpec. DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	if len(tokens) > 0 {
		sb.WriteString("// Token represents a lexical token generated by LangSpec\n")
		sb.WriteString("type Token string\n\n")
		sb.WriteString("const (\n")
		for _, t := range tokens {
			sb.WriteString(fmt.Sprintf("\t%s Token = \"%s\"\n", t, t))
		}
		sb.WriteString(")\n\n")
	}

	if len(nodes) > 0 {
		sb.WriteString("// Node represents a parsed AST Node generated by LangSpec\n")
		sb.WriteString("type Node string\n\n")
		sb.WriteString("const (\n")
		for _, n := range nodes {
			sb.WriteString(fmt.Sprintf("\t%s Node = \"%s\"\n", n, n))
		}
		sb.WriteString(")\n")
	}

	// 5. Write to disk
	if err := system.FileWriteString(outputPath, sb.String()); err != nil {
		return fmt.Errorf("failed to write go bindings file: %w", err)
	}

	return nil
}

func collectNodes[TToken, TNodeKind comparable](
	g *syntaxa.Grammar[TToken, TNodeKind],
	nodeSet map[string]bool,
	seen map[interface{}]bool,
) {
	if g == nil || seen[g] {
		return
	}
	seen[g] = true

	if g.OutputNodeKind != nil {
		nodeStr := fmt.Sprintf("%v", *g.OutputNodeKind)
		if nodeStr != "" {
			nodeSet[nodeStr] = true
		}
	}

	for _, child := range g.Children {
		collectNodes(child, nodeSet, seen)
	}
}
